"""pr_step5_chain.py -- adversarial numerical test of the Step-5 normalization chain
in a FINITE-DIMENSIONAL fermionic (CAR) model, full 2^n Jordan-Wigner Fock space.

Chain under test (all four should agree):
  (i)   inf_{h'=h'^*, h'=E_I' h' E_I'}  || P_-(D + i h') P_+ ||_HS^2
  (ii)  dist( a , M'_sa Omega )^2                    (M' = TRUE commutant of M)
  (iii) sup_{K in M_sa} [ phi(K) - Var(K) ]
  (iv)  (1/4) sup_{l=l^*, l on H_I} [ 2 Tr(Qdot l) - Tr(Q l (1-Q) l) ]
with a := -i :dGamma(D): Omega,  phi(K) := -2 Im<a, K Omega>.
Conventions (hermbasis / realvec) follow rigor/pa_step5_check.py.
"""
import numpy as np
from numpy.linalg import svd, norm
from scipy.linalg import expm

np.set_printoptions(precision=4, suppress=True)

# ---------------------------------------------------------------- helpers
def hermbasis(d):
    B = []
    for i in range(d):
        E = np.zeros((d, d), complex); E[i, i] = 1.0; B.append(E)
    for i in range(d):
        for j in range(i + 1, d):
            E = np.zeros((d, d), complex); E[i, j] = 1.0; E[j, i] = 1.0;  B.append(E)
            E = np.zeros((d, d), complex); E[i, j] = 1j;  E[j, i] = -1j;  B.append(E)
    return B

def realvec(X):
    X = np.asarray(X)
    return np.concatenate([X.real.ravel(), X.imag.ravel()])

def onb(cols, tol=1e-10):
    """orthonormal basis of the REAL column space of the real matrix `cols`"""
    if cols.shape[1] == 0:
        return np.zeros((cols.shape[0], 0))
    U, s, _ = svd(cols, full_matrices=False)
    r = int(np.sum(s > tol * max(1.0, s[0])))
    return U[:, :r]

def projsq(U, v):
    if U.shape[1] == 0:
        return 0.0
    c = U.T @ v
    return float(c @ c)

def reldiff(vals):
    vals = np.asarray(vals, float)
    sc = max(np.abs(vals).max(), 1e-300)
    return float((vals.max() - vals.min()) / sc)

# ---------------------------------------------------------------- JW / Fock
def jw(n):
    I2 = np.eye(2); Z = np.diag([1.0, -1.0]); sm = np.array([[0.0, 1.0], [0.0, 0.0]])
    ops = []
    for j in range(n):
        M = np.array([[1.0]])
        for k in range(n):
            M = np.kron(M, Z if k < j else (sm if k == j else I2))
        ops.append(M.astype(complex))
    return ops

def slater(aops, Uocc):
    """|Omega> = a^*(u_1)...a^*(u_p)|bare vac>, u_k = columns of Uocc"""
    n = len(aops); dim = aops[0].shape[0]
    v = np.zeros(dim, complex); v[0] = 1.0
    for k in range(Uocc.shape[1] - 1, -1, -1):
        ad = sum(Uocc[i, k] * aops[i].conj().T for i in range(n))
        v = ad @ v
    return v / norm(v)

def dGamma(T, aops):
    n = len(aops); dim = aops[0].shape[0]
    out = np.zeros((dim, dim), complex)
    for i in range(n):
        adi = aops[i].conj().T
        for j in range(n):
            if abs(T[i, j]) > 0:
                out += T[i, j] * (adi @ aops[j])
    return out

def a_of(f, aops):
    """a(f) = sum_i conj(f_i) a_i   (antilinear in f)"""
    return sum(np.conj(f[i]) * aops[i] for i in range(len(aops)))

# ---------------------------------------------------------------- structural checks
def commutant_dim_bruteforce(aops, m):
    """complex dim of {X : [X, a_i] = [X, a_i^*] = 0, i<=m}  (the *-commutant).
    NB: imposing only [X,a_i]=0 gives a strictly larger space -- the von Neumann
    algebra M is generated by the a_i AND their adjoints."""
    dim = aops[0].shape[0]; I = np.eye(dim)
    gens = [aops[i] for i in range(m)] + [aops[i].conj().T for i in range(m)]
    rows = [np.kron(g, I) - np.kron(I, g.T) for g in gens]
    Mm = np.vstack(rows)
    s = svd(Mm, compute_uv=False)
    r = int(np.sum(s > 1e-9 * max(1.0, s[0])))
    return dim * dim - r

def generated_algebra_dim(gens, dim):
    """complex dim of the unital algebra generated by `gens`"""
    def spandim(vs):
        A = np.array([v.ravel() for v in vs])
        s = svd(A, compute_uv=False)
        return int(np.sum(s > 1e-9 * max(1.0, s[0])))
    cur = [np.eye(dim, dtype=complex)] + list(gens)
    d_old = -1
    while True:
        d = spandim(cur)
        if d == d_old or d >= dim * dim:
            return d, cur
        d_old = d
        new = list(cur)
        for X in cur:
            for g in gens:
                new.append(X @ g)
        # keep it bounded: re-orthogonalise via SVD-selected representatives
        A = np.array([v.ravel() for v in new])
        U, s, Vt = svd(A, full_matrices=False)
        r = int(np.sum(s > 1e-9 * max(1.0, s[0])))
        cur = [Vt[k].reshape(dim, dim) for k in range(r)]

# ---------------------------------------------------------------- one instance
def run(n, p, m, seed, nK=50, verbose=True):
    rep = {}
    rng = np.random.default_rng(seed)
    dim = 1 << n; dI = 1 << m; dIp = 1 << (n - m)
    aops = jw(n); Ifock = np.eye(dim)

    # --- CAR relations
    car = 0.0
    for i in range(n):
        for j in range(n):
            car = max(car, norm(aops[i] @ aops[j].conj().T + aops[j].conj().T @ aops[i]
                                - (1.0 if i == j else 0.0) * Ifock))
    rep['CAR'] = car

    # --- Haar random rank-p projection, NOT aligned with the E_I splitting
    X = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    Qr, Rr = np.linalg.qr(X); Qr = Qr * (np.sign(np.diag(Rr).real) + 0.0)
    Uocc = Qr[:, :p]
    Pp = Uocc @ Uocc.conj().T; Pm = np.eye(n) - Pp
    Uemp = Qr[:, p:]
    EI = np.diag([1.0] * m + [0.0] * (n - m)).astype(complex); EIp = np.eye(n) - EI
    rep['nonalign'] = float(norm(EI @ Pp - Pp @ EI))     # must be >> 0

    Omega = slater(aops, Uocc)

    # --- two-point function check: <Om, a_i^* a_j Om> = (P_+)_{ji}
    R2 = np.array([[np.vdot(Omega, aops[i].conj().T @ aops[j] @ Omega) for j in range(n)]
                   for i in range(n)])
    rep['2pt'] = float(np.abs(R2 - Pp.T).max())
    # and in the f,g form: omega(a^*(f)a(g)) = <g, P_+ f>
    f = rng.normal(size=n) + 1j * rng.normal(size=n); g = rng.normal(size=n) + 1j * rng.normal(size=n)
    lhs = np.vdot(Omega, a_of(f, aops).conj().T @ a_of(g, aops) @ Omega)
    rep['2pt_fg'] = float(abs(lhs - np.vdot(g, Pp @ f)))

    # --- D skew-adjoint, Gamma(U)
    Y = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    D = (Y - Y.conj().T) / np.sqrt(n)
    rep['skew'] = float(norm(D + D.conj().T))
    dGD = dGamma(D, aops)
    Hh = 1j * dGD                                     # Hermitian
    rep['dG_skew'] = float(norm(dGD + dGD.conj().T))
    ev, V = np.linalg.eigh(Hh)
    def Gam(s):                                        # Gamma(exp(sD)) = exp(s dGamma(D))
        return (V * np.exp(-1j * s * ev)) @ V.conj().T
    W1 = expm(D); G1 = Gam(1.0)
    rep['Gam_unitary'] = float(norm(G1.conj().T @ G1 - Ifock))
    ff = rng.normal(size=n) + 1j * rng.normal(size=n)
    rep['Gam_cov'] = float(norm(G1 @ a_of(ff, aops) @ G1.conj().T - a_of(W1 @ ff, aops)))
    rep['Gam_vac'] = float(norm(G1[:, 0] - Ifock[:, 0]))   # fixes the BARE vacuum

    # --- normal-ordered generator and tangent vector
    trPDP = np.trace(Pp @ D @ Pp)
    rep['tr_re'] = float(trPDP.real); rep['tr_im'] = float(trPDP.imag)
    aU = -1j * (dGD @ Omega)                            # UNsubtracted
    aVec = -1j * (dGD @ Omega - trPDP * Omega)          # a = -i :dGamma(D): Omega

    def phi(Kvec_or_op, vec=False):
        KOm = Kvec_or_op if vec else (Kvec_or_op @ Omega)
        return -2.0 * np.imag(np.vdot(aVec, KOm))
    def phiU(KOm):
        return -2.0 * np.imag(np.vdot(aU, KOm))

    Om_mat = Omega.reshape(dI, dIp)                    # for K = H (x) 1 and B = 1 (x) Y

    # ---------------- C1 : phi(K) == d/ds omegat_s(K)|_0 ------------------
    h = 1e-3
    Psi = {s: Gam(-s * h) @ Omega for s in (-2, -1, 1, 2)}
    e1 = e1u = 0.0
    for _ in range(nK):
        Hm = rng.normal(size=(dI, dI)) + 1j * rng.normal(size=(dI, dI)); Hm = Hm + Hm.conj().T
        def KOmof(psi):
            return (Hm @ psi.reshape(dI, dIp)).ravel()
        vals = {s: float(np.real(np.vdot(Psi[s], KOmof(Psi[s])))) for s in (-2, -1, 1, 2)}
        fd = (vals[-2] - 8 * vals[-1] + 8 * vals[1] - vals[2]) / (12 * h)
        KOm = KOmof(Omega)
        e1 = max(e1, abs(phi(KOm, vec=True) - fd))
        e1u = max(e1u, abs(phiU(KOm) - fd))
    rep['C1'] = e1; rep['C1_unsub'] = e1u

    # ---------------- C2 : a in the (1,1) sector, a = -i P_- D P_+ --------
    dGpp = dGamma(Pp, aops); dGmm = dGamma(Pm, aops)
    rep['C2_nhole'] = float(norm(dGpp @ aVec - (p - 1) * aVec))
    rep['C2_npart'] = float(norm(dGmm @ aVec - 1.0 * aVec))
    Delta = Pm @ D @ Pp
    rep['C2_norm'] = abs(float(np.vdot(aVec, aVec).real) - float(norm(Delta) ** 2))
    # explicit HS identification in the (v_j, u_k) basis
    coef = np.zeros((n - p, p), complex); ortho = 0.0
    for k in range(p):
        for j in range(n - p):
            w = a_of(Uemp[:, j], aops).conj().T @ a_of(Uocc[:, k], aops) @ Omega
            ortho = max(ortho, abs(norm(w) - 1.0))
            coef[j, k] = np.vdot(w, aVec)
    rep['C2_ident'] = float(np.abs(coef - (-1j) * (Uemp.conj().T @ D @ Uocc)).max())
    rep['C2_onb'] = ortho
    rep['unsub_norm_gap'] = abs(float(np.vdot(aU, aU).real) - float(norm(Delta) ** 2))
    rep['unsub_Om_overlap'] = float(abs(np.vdot(Omega, aU)))

    # ---------------- Q, Qdot ---------------------------------------------
    Q = Pp[:m, :m].copy()
    Qdot_an = (Pp @ D - D @ Pp)[:m, :m]
    hq = 1e-4
    def Qt(s):
        Ws = expm(s * D); return (Ws.conj().T @ Pp @ Ws)[:m, :m]
    Qdot_fd = (Qt(-2 * hq) - 8 * Qt(-hq) + 8 * Qt(hq) - Qt(2 * hq)) / (12 * hq)
    rep['Qdot'] = float(np.abs(Qdot_an - Qdot_fd).max())
    rep['Qdot_herm'] = float(norm(Qdot_an - Qdot_an.conj().T))
    Qdot = Qdot_an

    # ---------------- C3 ---------------------------------------------------
    e3a = e3b = e3c = 0.0
    for _ in range(nK):
        l = rng.normal(size=(m, m)) + 1j * rng.normal(size=(m, m)); l = l + l.conj().T
        lE = np.zeros((n, n), complex); lE[:m, :m] = l
        dGl = dGamma(lE, aops)
        KOm = dGl @ Omega
        e3a = max(e3a, abs(phi(KOm, vec=True) - float(np.trace(Qdot @ l).real)))
        var = float((np.vdot(KOm, KOm) - abs(np.vdot(Omega, KOm)) ** 2).real)
        e3b = max(e3b, abs(var - float(np.trace(Q @ l @ (np.eye(m) - Q) @ l).real)))
        e3c = max(e3c, abs(var - float(norm(Pm @ lE @ Pp) ** 2)))
    rep['C3_phi'] = e3a; rep['C3_var_Q'] = e3b; rep['C3_var_HS'] = e3c

    # ---------------- (i) --------------------------------------------------
    hb_Ip = hermbasis(n - m)
    Kcols = []
    for hprime in hb_Ip:
        hh = np.zeros((n, n), complex); hh[m:, m:] = hprime
        Kcols.append(realvec(1j * (Pm @ hh @ Pp)))       # i*h' perturbation
    Kcols = np.array(Kcols).T
    dvec = realvec(Delta)
    UK = onb(Kcols)
    val_i = float(dvec @ dvec) - projsq(UK, dvec)
    # sanity: same by explicit lstsq
    sol, *_ = np.linalg.lstsq(Kcols, -dvec, rcond=None)
    rep['i_lstsq_gap'] = abs(val_i - float(norm(Kcols @ sol + dvec) ** 2))

    # ---------------- (ii) and (ii') --------------------------------------
    hb_Ip_full = hermbasis(dIp)
    Vcols = np.array([realvec((Om_mat @ Yk.T).ravel()) for Yk in hb_Ip_full]).T
    avec_r = realvec(aVec)
    val_ii = float(avec_r @ avec_r) - projsq(onb(Vcols), avec_r)
    # untwisted algebra N generated by a(f), f in H_I' :
    #   N = (1 (x) even) + Theta*(1 (x) odd),  Theta = Z^{(x)m} (x) 1
    zsign = np.array([(-1.0) ** bin(k).count('1') for k in range(dI)])
    zsign_Ip = np.array([(-1.0) ** bin(k).count('1') for k in range(dIp)])
    Ncols = []
    for Yk in hb_Ip_full:
        par = zsign_Ip[:, None] * Yk * zsign_Ip[None, :]
        if np.allclose(par, Yk):                     # even
            Ncols.append(realvec((Om_mat @ Yk.T).ravel()))
        elif np.allclose(par, -Yk):                  # odd -> multiply by Theta
            Ncols.append(realvec((zsign[:, None] * (Om_mat @ Yk.T)).ravel()))
        else:
            raise RuntimeError('basis element not parity-homogeneous')
    Ncols = np.array(Ncols).T
    val_iip = float(avec_r @ avec_r) - projsq(onb(Ncols), avec_r)
    # verify the structural description of N against the JW generators
    bops = jw(n - m) if n - m > 0 else []
    Theta = np.kron(np.diag(zsign), np.eye(dIp))
    egen = 0.0
    for j in range(m, n):
        egen = max(egen, norm(aops[j] - Theta @ np.kron(np.eye(dI), bops[j - m])))
    rep['N_struct'] = egen
    # do the two algebras differ at all?
    rep['MN_diff'] = float(norm(onb(Vcols) @ onb(Vcols).T - onb(Ncols) @ onb(Ncols).T))

    # ---------------- (iii) -------------------------------------------------
    hb_I_full = hermbasis(dI)
    Scols = []
    fvec = []
    for Hk in hb_I_full:
        KOm = (Hk @ Om_mat).ravel()
        x = KOm - np.vdot(Omega, KOm) * Omega
        Scols.append(realvec(x)); fvec.append(phi(KOm, vec=True))
    Scols = np.array(Scols).T; fvec = np.array(fvec)
    rep['dimM_Om'] = onb(np.array([realvec((Hk @ Om_mat).ravel())
                                   for Hk in hb_I_full]).T).shape[1]
    rep['dimM_sa'] = 4 ** m; rep['dimMp_sa'] = 4 ** (n - m)
    bvec = realvec(-1j * aVec)
    val_iii = projsq(onb(Scols), bvec)
    # independent route: explicit concave quadratic maximisation
    Gq = Scols.T @ Scols
    c, *_ = np.linalg.lstsq(Gq, fvec / 2.0, rcond=None)
    val_iii_direct = float(fvec @ c - c @ Gq @ c)
    rep['iii_route_gap'] = abs(val_iii - val_iii_direct) / max(abs(val_iii), 1e-300)

    # ---------------- (iv) -------------------------------------------------
    hb_I = hermbasis(m)
    tv = np.array([2.0 * float(np.trace(Qdot @ l).real) for l in hb_I])
    Lemb = []
    for l in hb_I:
        lE = np.zeros((n, n), complex); lE[:m, :m] = l
        Lemb.append(realvec(Pm @ lE @ Pp))
    Lemb = np.array(Lemb).T
    Gl = Lemb.T @ Lemb
    cl, *_ = np.linalg.lstsq(Gl, tv / 2.0, rcond=None)
    sup_QL = float(tv @ cl - cl @ Gl @ cl)
    val_iv = sup_QL / 4.0
    cl2, *_ = np.linalg.lstsq(Gl, -tv / 2.0, rcond=None)
    sup_QL_neg = float((-tv) @ cl2 - cl2 @ Gl @ cl2)
    rep['iv_signflip'] = abs(sup_QL - sup_QL_neg) / max(abs(sup_QL), 1e-300)
    # analytic cross-check: (iv) should be ||Proj_{L_set} Delta||^2
    rep['iv_proj_gap'] = abs(val_iv - projsq(onb(Lemb), dvec)) / max(abs(val_iv), 1e-300)
    # orthogonality of L_set and i*K_set (the pa_step5_check.py structure)
    rep['LK_orth'] = float(np.abs(onb(Lemb).T @ onb(Kcols)).max()) if Kcols.shape[1] else 0.0

    # ---------------- identification of M and its commutant ----------------
    # (A) a_i = atilde_i (x) 1 for i<=m, so M = M_{2^m} (x) 1
    at = jw(m)
    rep['M_fac'] = max(norm(aops[i] - np.kron(at[i], np.eye(dIp))) for i in range(m))
    # (B) {atilde_i, atilde_i^*} generate ALL of M_{2^m}
    dM, _ = generated_algebra_dim([x for i in range(m) for x in (at[i], at[i].conj().T)], dI)
    rep['Mdim'] = dM; rep['Mdim_exp'] = 4 ** m
    # (D) every 1 (x) Y commutes with a_i and a_i^*, i<=m
    eD = 0.0
    for Yk in hb_Ip_full[:min(len(hb_Ip_full), 40)]:
        B = np.kron(np.eye(dI), Yk)
        for i in range(m):
            eD = max(eD, norm(B @ aops[i] - aops[i] @ B),
                     norm(B @ aops[i].conj().T - aops[i].conj().T @ B))
    rep['Mprime_comm'] = eD
    # (E) N is NOT contained in M' : a_j (j>m) anticommutes with a_i (i<=m)
    rep['N_noncomm'] = max(norm(aops[m] @ aops[i] - aops[i] @ aops[m]) for i in range(m))
    # projections of a onto the two subspaces
    UV = onb(Vcols); UN = onb(Ncols)
    rep['dimMp'] = UV.shape[1]; rep['dimN'] = UN.shape[1]
    rep['projdiff'] = float(norm(UV @ (UV.T @ avec_r) - UN @ (UN.T @ avec_r)))
    # (C) brute-force *-commutant, small n only
    if dim <= 32:
        rep['commdim'] = commutant_dim_bruteforce(aops, m)
        rep['commdim_exp'] = 4 ** (n - m)
        dN, _ = generated_algebra_dim([aops[j] for j in range(m, n)] +
                                      [aops[j].conj().T for j in range(m, n)], dim)
        rep['Ndim'] = dN; rep['Ndim_exp'] = 4 ** (n - m)

    rep.update(n=n, p=p, m=m, i=val_i, ii=val_ii, iip=val_iip, iii=val_iii, iv=val_iv)
    rep['rel_4'] = reldiff([val_i, val_ii, val_iii, val_iv])
    rep['rel_iip_vs_i'] = abs(val_iip - val_i) / max(abs(val_i), 1e-300)
    return rep

# ---------------------------------------------------------------- driver
if __name__ == '__main__':
    INST = [(4, 2, 2), (6, 3, 3), (6, 2, 3), (6, 3, 2), (8, 4, 4), (8, 3, 5)]
    print('=' * 100)
    print('SETUP / STRUCTURAL VERIFICATIONS  (max abs errors)')
    print('=' * 100)
    hdr = ('(n,p,m)      CAR      2pt      2pt(f,g)  Gam:unit  Gam:cov  Gam:vac  '
           'skew(D)  [EI,P+]   N-struct')
    print(hdr)
    reps = []
    for (n, p, m) in INST:
        r = run(n, p, m, seed=1000 * n + 10 * p + m)
        reps.append(r)
        print(f"({n},{p},{m})    {r['CAR']:.1e}  {r['2pt']:.1e}  {r['2pt_fg']:.1e}   "
              f"{r['Gam_unitary']:.1e}  {r['Gam_cov']:.1e}  {r['Gam_vac']:.1e}  "
              f"{r['skew']:.1e}  {r['nonalign']:.3f}   {r['N_struct']:.1e}")
    print()
    print('=' * 100)
    print('C1  d/ds omega~_s(K)|_0 == phi(K)   (50 random K in M_sa, 5-pt FD, h=1e-3)')
    print('=' * 100)
    print('(n,p,m)      max|phi-FD| (normal-ordered)   max|phi-FD| (UNsubtracted)   '
          'Tr(P+DP+) = re + i*im')
    for r in reps:
        print(f"({r['n']},{r['p']},{r['m']})    {r['C1']:.3e}                      "
              f"{r['C1_unsub']:.3e}                    {r['tr_re']:+.2e} + i*{r['tr_im']:+.4f}")
    print()
    print('=' * 100)
    print('C2  a = -i :dGamma(D): Omega  lies in H^(1,1) and equals -i P_-DP_+')
    print('=' * 100)
    print('(n,p,m)   N_part a=a   N_hole a=(p-1)a   ||a||^2-||P-DP+||^2   coef==-iP-DP+   '
          '| UNSUB: <Om,a_u>   ||a_u||^2-||P-DP+||^2')
    for r in reps:
        print(f"({r['n']},{r['p']},{r['m']})   {r['C2_npart']:.1e}      {r['C2_nhole']:.1e}"
              f"          {r['C2_norm']:.2e}             {r['C2_ident']:.1e}         "
              f"| {r['unsub_Om_overlap']:.4f}          {r['unsub_norm_gap']:.4f}")
    print()
    print('=' * 100)
    print('C3  phi(dGamma(l))=Tr(Qdot l),  Var=Tr(Ql(1-Q)l)=||P-lP+||^2  (50 random l=l^*)')
    print('=' * 100)
    print('(n,p,m)   Qdot(an vs FD)  Qdot herm   max|phi-Tr(Qdot l)|  max|Var-Tr(Ql(1-Q)l)|  '
          'max|Var-||P-lP+||^2|')
    for r in reps:
        print(f"({r['n']},{r['p']},{r['m']})   {r['Qdot']:.2e}        {r['Qdot_herm']:.1e}    "
              f"{r['C3_phi']:.3e}            {r['C3_var_Q']:.3e}             {r['C3_var_HS']:.3e}")
    print()
    print('=' * 100)
    print('C4  THE CHAIN:  (i) inf_h\' ||P-(D+ih\')P+||^2 | (ii) dist(a,M\'_sa Om)^2 | '
          '(iii) sup[phi-Var] | (iv) (1/4)sup Omega_QL')
    print('=' * 100)
    print('(n,p,m)        (i)            (ii)           (iii)          (iv)        '
          'max rel diff   sign-flip  (iv)vsProj_L  (iii)routes  max<L,iK>')
    for r in reps:
        print(f"({r['n']},{r['p']},{r['m']})   {r['i']:.10f}  {r['ii']:.10f}  {r['iii']:.10f}  "
              f"{r['iv']:.10f}   {r['rel_4']:.2e}      {r['iv_signflip']:.1e}   "
              f"{r['iv_proj_gap']:.1e}      {r['iii_route_gap']:.1e}   {r['LK_orth']:.1e}")
    print()
    print('=' * 100)
    print("C5  TRUE commutant M' (twisted)  vs  untwisted N = alg{a(f): f in H_I'}")
    print('=' * 100)
    print("(n,p,m)     (ii)=dist(a,M'_saOm)^2   (ii')=dist(a,N_saOm)^2   |(ii)-(ii')|   "
          "rel|(ii')-(i)|   dim_R  ||P_M'-P_N||  ||P_M'a-P_N a||")
    for r in reps:
        print(f"({r['n']},{r['p']},{r['m']})   {r['ii']:.10f}          {r['iip']:.10f}"
              f"       {abs(r['ii']-r['iip']):.2e}      {r['rel_iip_vs_i']:.2e}      "
              f"{r['dimMp']}/{r['dimN']}   {r['MN_diff']:.3f}       {r['projdiff']:.3e}")
    print()
    print("structural: M = M_{2^m}(x)1 ?  M' = 1(x)M_{2^(n-m)} ?  N not in M' ?")
    print("(n,p,m)   a_i=at_i(x)1   dim M (=?4^m)   [1(x)Y, a_i]=0   ||[a_{m+1},a_1]||>0   "
          "brute *-commutant dim (=?4^(n-m)) / dim N")
    for r in reps:
        extra = (f"{r['commdim']} =? {r['commdim_exp']}  /  {r['Ndim']} =? {r['Ndim_exp']}"
                 if 'commdim' in r else 'n/a (dim too large)')
        print(f"({r['n']},{r['p']},{r['m']})   {r['M_fac']:.1e}        "
              f"{r['Mdim']} =? {r['Mdim_exp']}      {r['Mprime_comm']:.1e}          "
              f"{r['N_noncomm']:.3f}               {extra}")
    print()
    print('=' * 100)
    print('VERDICT')
    print('=' * 100)
    tolFD = 1e-6; tolLA = 1e-8
    ok = lambda b: 'PASS' if b else 'FAIL'
    c1  = all(r['C1'] < tolFD for r in reps)
    c1u = all(r['C1_unsub'] < tolFD for r in reps)
    c2  = all(max(r['C2_npart'], r['C2_nhole'], r['C2_norm'], r['C2_ident']) < 1e-9 for r in reps)
    c3  = all(max(r['C3_phi'], r['C3_var_Q'], r['C3_var_HS']) < 1e-9 for r in reps)
    c4  = all(r['rel_4'] < tolLA for r in reps)
    c4s = all(r['iv_signflip'] < tolLA for r in reps)
    c5  = all(abs(r['ii'] - r['iip']) < 1e-9 for r in reps)
    print(f"C1  phi = d/ds omega~_s          : {ok(c1)}   (max {max(r['C1'] for r in reps):.2e})")
    print(f"C1' same with UNSUBTRACTED dG(D) : {ok(c1u)}  (max {max(r['C1_unsub'] for r in reps):.2e})"
          "  -> normal ordering is INVISIBLE to phi (Tr(P+DP+) is purely imaginary)")
    print(f"C2  a in H^(1,1), a = -i P-DP+   : {ok(c2)}   "
          f"(unsub. fails: ||a_u||^2 exceeds by |Tr P+DP+|^2, max {max(r['unsub_norm_gap'] for r in reps):.3f})")
    print(f"C3  phi/Var vs Q, Qdot           : {ok(c3)}")
    print(f"C4  (i)=(ii)=(iii)=(iv)          : {ok(c4)}   (max rel diff {max(r['rel_4'] for r in reps):.2e})")
    print(f"C4  sign-insensitivity of sup    : {ok(c4s)}")
    print("     Omega separating?  dim_R M_sa.Om vs 4^m  |  dim_R M'_sa.Om vs 4^(n-m) :")
    for r in reps:
        sM = 'yes' if r['dimM_Om'] == r['dimM_sa'] else 'NO '
        sP = 'yes' if r['dimMp'] == r['dimMp_sa'] else 'NO '
        print(f"       ({r['n']},{r['p']},{r['m']})  M: {r['dimM_Om']:>5}/{r['dimM_sa']:<5} {sM}"
              f"   M': {r['dimMp']:>4}/{r['dimMp_sa']:<5} {sP}")
    print(f"C5  twisted vs untwisted commutant: (ii)==(ii') {ok(c5)}   "
          f"max|diff| {max(abs(r['ii']-r['iip']) for r in reps):.2e}; "
          f"but the SUBSPACES differ (||P_M'-P_N||>0): "
          f"{all(r['MN_diff'] > 1e-6 for r in reps)}")
