#!/usr/bin/env python3
"""Build docs/data/extra-*.json for modules 7-10 of the interactive site.

Companion to tools/build_site_data.py, which owns docs/data/{constants,
quadratic-law,theta,networks}.json.  This one writes only files whose name
begins with `extra-`, so the two generators never touch each other's output:

    extra-separation.json      module 7, the separation constraint
    extra-off-criticality.json module 8, gap, temperature and mass
    extra-relative-entropy.json module 9, the s2 conjecture and its bracket
    extra-claim-map.json       module 10, the knowledge base as a graph

Every record is

    {"value": <float|null>, "error": <float|null>, "source": "<repo path>",
     "line": <1-based line number>, "status": "<proved|certified|numerical|...>"}

and the page refuses to print a number that has no source.  Nothing is read
from docs/results/*.md: those pages are generated by tools/build_docs.py from
the knowledge base, so sourcing a number there would only echo a copy.

Two rules this file exists to keep:

*   `--check` is byte-exact and exits non-zero on drift.  The output carries no
    timestamp, so a difference means a source file moved under the JSON.
*   every unit, scale factor or column meaning taken from a table is asserted
    to be still declared by that table (`declare` and `header` below).  A
    silently renamed column then fails the build instead of rescaling a number.

Usage
-----
    python3 tools/build_site_data_extra.py            # write docs/data/extra-*.json
    python3 tools/build_site_data_extra.py --check    # re-extract, diff, exit 1 on drift
"""
from __future__ import annotations

import argparse
import json
import math
import re
import subprocess
import unicodedata
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "docs" / "data"
KB = ROOT.parent / "kb" / "projects" / "cft_cmi"

_NUM = r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?"


class Drift(Exception):
    """A source file no longer says what the extractor was told it says."""


# --------------------------------------------------------------------- basics
def read(relpath: str):
    """Return (relpath, [lines]).  Raises if the source has disappeared."""
    p = ROOT / relpath
    if not p.is_file():
        raise Drift("source file missing: %s" % relpath)
    return relpath, p.read_text(encoding="utf-8").splitlines()


def q(x):
    """Round to 12 significant digits: enough for every source read here, and
    it keeps arithmetic on the parsed values free of binary dust."""
    if isinstance(x, float) and math.isfinite(x):
        return float("%.12g" % x)
    if isinstance(x, float):
        return None                      # nan / inf never reach the page
    return x


def record(rid, value, error, source, line, status, **extra):
    r = {"value": q(value), "error": q(error), "source": source,
         "line": line, "status": status, "id": rid}
    r.update({k: v for k, v in extra.items() if v is not None})
    return r


def declare(relpath, lines, needle, why):
    """Assert that the file still declares a unit, scale or convention this
    extractor relies on, and return the line it is declared on.  `needle` is
    matched literally except that any run of whitespace matches any other, so a
    declaration that wraps over two lines still counts."""
    pat = re.compile(r"\s+".join(re.escape(w) for w in needle.split()))
    text = "\n".join(lines)
    m = pat.search(text)
    if m is None:
        raise Drift("%s no longer declares %r (needed for %s)" % (relpath, needle, why))
    return text.count("\n", 0, m.start()) + 1


def header(relpath, lines, pattern, why, start=0):
    """Return the 0-based index of the column header matching `pattern`.
    Reading a column by position is only safe while the header still names it."""
    rx = re.compile(pattern)
    for i in range(start, len(lines)):
        if rx.search(lines[i]):
            return i
    raise Drift("%s: no column header matching %r (needed for %s)"
                % (relpath, pattern, why))


def nums(line):
    """Every number on a line, in order.  'nan' comes back as None."""
    out = []
    for tok in re.findall(r"nan|%s" % _NUM, line):
        out.append(None if tok == "nan" else float(tok))
    return out


def dump(name: str, payload: dict, check: bool) -> bool:
    """Write (or verify) docs/data/<name>.  Returns True when in step."""
    check_payload(name, payload)
    text = json.dumps(payload, indent=1, ensure_ascii=False, sort_keys=False) + "\n"
    path = DATA / name
    if check:
        if not path.is_file():
            print("MISSING  docs/data/%s" % name)
            return False
        if path.read_text(encoding="utf-8") != text:
            print("DRIFTED  docs/data/%s (re-extraction differs from the committed file)" % name)
            return False
        print("ok       docs/data/%s" % name)
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print("wrote    docs/data/%s  (%d records)" % (name, len(payload.get("records", []))))
    return True


# ==========================================================================
# module 7 — the separation constraint, Theorem 11.1
# ==========================================================================

def build_separation():
    """docs/data/extra-separation.json.

    The exact constrained minima of e^{Delta_k} under "every corner to the
    right is weak", against the bound 2/eps of Theorem 11.1.  The bound is
    approached and never attained: the ratio column is the whole point."""
    records = []

    src, lines = read("rigor/ref_p6_3_separation.out")
    declare(src, lines, "EXACT minimum of e^{Delta_k} over all-weak chains "
                        "(m = number of corners j >= k)",
            "the meaning of the m columns")
    h = header(src, lines,
               r"^\s*eps\s+m=1\s+m=2\s+m=3\s+m=10\s+m->inf\s+2/eps\s+ratio\s*$",
               "the exact-minimum table")
    cols = ["m1", "m2", "m3", "m10", "inf"]
    seen = 0
    for i in range(h + 1, len(lines)):
        v = nums(lines[i])
        if len(v) != 8:
            break
        seen += 1
        eps, ln1 = v[0], i + 1
        for j, key in enumerate(cols):
            records.append(record(
                "sep.min.%s.%s" % (key, eps), v[1 + j], None, src, ln1, "numerical",
                series="min_" + key, x=eps,
                label=("exact constrained minimum of e^{Delta_k}, %s corners to the right, eps = %s"
                       % ({"inf": "arbitrarily many"}.get(key, key[1:]), eps))))
        records.append(record("sep.bound.%s" % eps, v[6], None, src, ln1, "proved",
                              series="bound", x=eps,
                              label="the bound 2/eps of Theorem 11.1 at eps = %s" % eps))
        records.append(record("sep.ratio.%s" % eps, v[7], None, src, ln1, "numerical",
                              series="ratio", x=eps,
                              label="(eps/2) times the exact minimum at eps = %s: 1 would be attainment"
                                    % eps))
    if seen != 5:
        raise Drift("%s: expected 5 rows of exact minima, read %d" % (src, seen))

    # the checks that say the theorem is never violated, and the escape routes
    for rid, pat, status, label in [
        ("sep.check.random_exact",
         r"separation e\^\{Delta_k\} >= 2/eps\s+\(0 violations, min \(eps/2\)e\^\{Delta\} = (%s)\)" % _NUM,
         "numerical", "min (eps/2)e^{Delta_k} over 60000 exact rational chains (REF-P6-3)"),
        ("sep.check.admissible",
         r"Cor 11\.2: eps e\^\{Delta_k\} >= 1 for admissible s_j \(min = (%s)\)" % _NUM,
         "numerical", "min eps e^{Delta_k} for admissible s_j in [lambda, 2 lambda] (Corollary 11.2)"),
        ("sep.check.pair_only",
         r"the separation stays O\(1\): min e\^\{Delta_k\} found = (%s)" % _NUM,
         "numerical", "with only the PAIR of corners weak at eps = 0.01: the separation stays O(1), "
                      "against 2/eps = 200"),
    ]:
        rx = re.compile(pat)
        for i, ln in enumerate(lines):
            m = rx.search(ln)
            if m:
                records.append(record(rid, float(m.group(1)), None, src, i + 1, status,
                                      series="check", label=label))
                break
        else:
            raise Drift("%s: no line matching %r" % (src, pat))

    src2, lines2 = read("rigor/g1a_separation.out")
    for rid, pat, label in [
        ("sep.check.random_float",
         r"min over 400000 random chains of \(eps/2\) e\^\{D_k\} = (%s)" % _NUM,
         "min (eps/2)e^{Delta_k} over 400000 random chains (G1a)"),
        ("sep.check.last_corner",
         r"min over the same chains of e\^\{D_\{n-1\}\}/\(1\+2/zeta_\{n-1\}\) = (%s)" % _NUM,
         "e^{Delta_{n-1}}/(1+2/zeta_{n-1}) over the same chains: the last corner is an equality"),
    ]:
        rx = re.compile(pat)
        for i, ln in enumerate(lines2):
            m = rx.search(ln)
            if m:
                records.append(record(rid, float(m.group(1)), None, src2, i + 1, "numerical",
                                      series="check", label=label))
                break
        else:
            raise Drift("%s: no line matching %r" % (src2, pat))

    return {
        "generator": "tools/build_site_data_extra.py",
        "module": "separation",
        "note": ("Theorem 11.1 of rigor/network_corner_calculus.tex and the exact constrained "
                 "minima REF-P6-3 computed from the backward recursion of Lemma 10.3.  The module "
                 "runs the same recursion live, so its own curve can be read against these "
                 "numbers; m is the number of corners to the right of p_k."),
        "records": records,
    }


# ==========================================================================
# module 8 — off criticality: gap, temperature, mass
# ==========================================================================

THERMAL = "numerics/lattice/petz_thermal_rg.out"


def _rows_after(lines, h, count):
    """Yield (1-based line number, [numbers]) for the rows that follow the
    column header at index `h` and still have `count` numbers on them."""
    for i in range(h + 1, len(lines)):
        v = nums(lines[i])
        if len(v) != count:
            return
        yield i + 1, v


def _thermal(records):
    """Section (1): -log F and the CMI of a KMS state against L_B/beta, and
    section (1a): the fitted shielding rates."""
    src, lines = read(THERMAL)
    declare(src, lines,
            "L_A = L_C = L, L_B = b, v = 2, beta_len = 2 beta, xi = beta/pi",
            "the thermal length units of the b/beta axis")
    blk = re.compile(r"^\s*L_A=L_C=(\d+)\s+beta=([\d.]+)\s*$")
    hdr = (r"^\s*b/beta\s+-logF\^\(0\)\s+/vacuum\s+CMI\s+CMI_cont\s+kap_F\s+kap_I"
           r"\s+kap_Ic\s+ratio 2br\s*$")
    blocks = 0
    for i, ln in enumerate(lines):
        m = blk.match(ln)
        if not m or m.group(1) != "8":
            continue                      # one geometry on the page: L_A = L_C = 8
        L, beta = m.group(1), m.group(2)
        h = header(src, lines, hdr, "the thermal table at beta = %s" % beta, start=i)
        if h != i + 1:
            raise Drift("%s: the column header does not follow the block line at %d" % (src, i + 1))
        blocks += 1
        for ln1, v in _rows_after(lines, h, 9):
            x = v[0]
            records.append(record("th.phi.b%s.%s" % (beta, x), v[1], None, src, ln1, "numerical",
                                  series="thermal.phi.b" + beta, x=x,
                                  label="-log F^(0) at L_B/beta = %s, beta = %s, L_A = L_C = %s"
                                        % (x, beta, L)))
            records.append(record("th.cmi.b%s.%s" % (beta, x), v[3], None, src, ln1, "numerical",
                                  series="thermal.cmi.b" + beta, x=x,
                                  label="I(A:C|B) at L_B/beta = %s, beta = %s, L_A = L_C = %s"
                                        % (x, beta, L)))
    if blocks != 4:
        raise Drift("%s: expected 4 finite-beta thermal blocks at L = 8, found %d" % (src, blocks))

    declare(src, lines, "fit -log F^(0) = A exp(-kappa_F L_B/beta)",
            "the rate kappa is measured in units of beta")
    declare(src, lines, "kappa_I = pi = 3.14159 and, if -log F ~ eta^2, kappa_F = 2 pi = 6.28319",
            "the continuum values the fitted rates are read against")
    h = header(src, lines,
               r"^\s*L\s+beta\s+#pts\s+kappa_F\s+A_F\s+kappa_I\s+A_I\s+kappa_F/kappa_I"
               r"\s+kappa_I\(cont\)\s*$", "the shielding-rate fits")
    fits = 0
    for ln1, v in _rows_after(lines, h, 9):
        fits += 1
        tag = "L%d.b%s" % (int(v[0]), v[1])
        records.append(record("th.kapF." + tag, v[3], None, src, ln1, "numerical",
                              series="rate.kapF", x=v[1], L=v[0],
                              label="fitted kappa_F at L = %d, beta = %s (continuum 2 pi)"
                                    % (int(v[0]), v[1])))
        records.append(record("th.kapI." + tag, v[5], None, src, ln1, "numerical",
                              series="rate.kapI", x=v[1], L=v[0],
                              label="fitted kappa_I at L = %d, beta = %s (continuum pi)"
                                    % (int(v[0]), v[1])))
    if fits != 6:
        raise Drift("%s: expected 6 rows of shielding fits, read %d" % (src, fits))


def _cfunction(records):
    """Section (2): the entropic and Markov c-functions along the massive flow."""
    src, lines = read(THERMAL)
    declare(src, lines, "staggered mass m, mu = m/2, xi = 2/m sites, RG variable mu R = m R/2",
            "the RG variable mu R of the c-function axis")
    declare(src, lines, "PRIMARY DEFINITION c_M := c_M^(2) = 3R^2 I_{R-2}(2)/4",
            "which column is the Markov c-function")
    blk = re.compile(r"^\s*m = ([\d.]+)\s+xi = (\S+) sites\s*$")
    hdr = (r"^\s*R\s+mu R\s+c_E\s+c_M=c_M\^\(2\)\s+c_M\^\(4\)\s+c_M\^\(Rich\)\s+c_M/c_E"
           r"\s+\(c_M/c_E\)/\(mR\)\s+dc_E\s+dc_M\s*$")
    masses = []
    for i, ln in enumerate(lines):
        m = blk.match(ln)
        if not m:
            continue
        mass = m.group(1)
        h = header(src, lines, hdr, "the c-function table at m = %s" % mass, start=i)
        if h != i + 1:
            raise Drift("%s: the c-function header does not follow the block line at %d"
                        % (src, i + 1))
        masses.append(mass)
        for ln1, v in _rows_after(lines, h, 10):
            R = int(v[0])
            records.append(record("cf.cE.m%s.R%d" % (mass, R), v[2], None, src, ln1, "numerical",
                                  series="cfun.cE.m" + mass, x=v[1], R=R,
                                  label="entropic c_E(R = %d) at m = %s" % (R, mass)))
            records.append(record("cf.cM.m%s.R%d" % (mass, R), v[3], None, src, ln1, "numerical",
                                  series="cfun.cM.m" + mass, x=v[1], R=R,
                                  label="Markov c_M(R = %d) at m = %s" % (R, mass)))
            records.append(record("cf.rmr.m%s.R%d" % (mass, R), v[7], None, src, ln1, "numerical",
                                  series="cfun.ratio_mR.m" + mass, x=v[1], R=R,
                                  label="(c_M/c_E)/(mR) at R = %d, m = %s: the IR prediction is 1"
                                        % (R, mass)))
    if masses != ["0.0000", "0.0500", "0.1000", "0.2000", "0.4000", "0.8000", "1.6000"]:
        raise Drift("%s: the mass ladder of section (2) changed: %r" % (src, masses))
    return masses


def _gap(records):
    """Section (3): the gap geometry A | G | B | C with G traced out."""
    src, lines = read(THERMAL)
    declare(src, lines,
            "I(A:C|B) = (1/3) log[(a+g+b)(g+b+c)/((g+b)(a+g+b+c))],",
            "the closed-form gap law the module evaluates live")
    declare(src, lines, "eta_g = a c/[(a+g+b)(g+b+c)] -> a c/L_G^2, so I ~ L_G^-2, -logF ~ L_G^-4",
            "the naive expectation the measurement contradicts")
    # The three gap tables carry no L column: the driver decides, and it is the
    # only place that says so, so the lengths are read from there and guarded.
    drv, dlines = read("numerics/lattice/petz_thermal_rg.py")
    ln = declare(drv, dlines, "for L in (6, 8, 12): rows += gap_scan(L=L,",
                 "which interval length each of the three gap tables belongs to")
    lengths = [int(x) for x in re.findall(r"\d+", dlines[ln - 1].split("(")[1].split(")")[0])]
    if lengths != [6, 8, 12]:
        raise Drift("%s:%d: the gap scan no longer runs L = 6, 8, 12" % (drv, ln))

    at, total = 0, 0
    for L in lengths:
        h = header(src, lines,
                   r"^\s*L_G\s+eta_g\s+I\(A:C\|B\)\s+I_cont\s+I/I_cont\s+-logF\^\(0\)\s+-logF\^\(1\)"
                   r"\s+ratio 2br\s+p_I\s+p_F\s+-logF/I\s+norm\s*$",
                   "the gap table at L = %d" % L, start=at)
        at = h + 1
        rows = 0
        for ln1, v in _rows_after(lines, h, 12):
            rows += 1
            g = int(v[0])
            records.append(record("gap.I.L%d.%d" % (L, g), v[2], None, src, ln1, "numerical",
                                  series="gap.I.L%d" % L, x=g, L=L,
                                  label="measured I(A:C|B) at L_G = %d, L_A = L_B = L_C = %d" % (g, L)))
            records.append(record("gap.Icont.L%d.%d" % (L, g), v[3], None, src, ln1, "numerical",
                                  series="gap.Icont.L%d" % L, x=g, L=L,
                                  label="the closed-form gap law at L_G = %d, L = %d" % (g, L)))
            records.append(record("gap.phi.L%d.%d" % (L, g), v[5], None, src, ln1, "numerical",
                                  series="gap.phi.L%d" % L, x=g, L=L,
                                  label="-log F^(0) at L_G = %d, L = %d" % (g, L)))
            records.append(record("gap.ratio.L%d.%d" % (L, g), v[10], None, src, ln1, "numerical",
                                  series="gap.ratio.L%d" % L, x=g, L=L,
                                  label="-log F^(0) / I at L_G = %d, L = %d: the ratio tends to a "
                                        "constant, so the decay is linear in the CMI, not quadratic"
                                        % (g, L)))
        if rows != 14:
            raise Drift("%s: expected 14 rows of gap geometry at L = %d, read %d" % (src, L, rows))
        total += rows
    if total != 42:
        raise Drift("%s: expected three gap tables, read %d rows" % (src, total))


def _two_branch(records):
    """The lattice exponents of -log F^(lambda) ~ eta^p."""
    src, lines = read("numerics/lattice/petz_lattice.out")
    declare(src, lines, "apparent exponents p of -log F^(lam) ~ eta^p (least squares in log-log)",
            "what the exponent columns measure")
    h = header(src, lines,
               r"^\s*lambda\s+eta<=0\.1\s+0\.02-0\.2\s+0\.05-0\.5\s+\|\s+VWZ fit\s+Note 5\s*$",
               "the two-branch exponent table")
    rows = 0
    for i in range(h + 1, len(lines)):
        m = re.match(r"^\s*(%s)\s+(%s)\s+(%s)\s+(%s)\s+\|\s+(%s)\s+(%s)\s" % ((_NUM,) * 6), lines[i])
        if not m:
            break
        rows += 1
        lam = m.group(1)
        records.append(record("tb.p.%s" % lam, float(m.group(2)), None, src, i + 1, "numerical",
                              series="twobranch.lattice", x=float(lam),
                              label="lattice exponent p at lambda = %s, fitted over eta <= 0.1" % lam))
        records.append(record("tb.vwz.%s" % lam, float(m.group(5)), None, src, i + 1, "numerical",
                              series="twobranch.vwz", x=float(lam),
                              label="the Vardhan-Wei-Zou fitted exponent at lambda = %s" % lam))
    if rows != 4:
        raise Drift("%s: expected 4 rows of exponents, read %d" % (src, rows))


def build_off_criticality():
    """docs/data/extra-off-criticality.json."""
    records = []
    _thermal(records)
    masses = _cfunction(records)
    _gap(records)
    _two_branch(records)
    return {
        "generator": "tools/build_site_data_extra.py",
        "module": "off-criticality",
        "masses": masses,
        "note": ("Lattice measurements of the free fermion off criticality: KMS states, the "
                 "massive flow and the gap geometry, all from numerics/lattice/petz_thermal_rg.out "
                 "and petz_lattice.out.  The closed forms the module evaluates live (the gap law "
                 "and the thermal cross ratio) are exact; everything in this file is measured."),
        "records": records,
    }


# ==========================================================================
# module 9 — relative entropy: the conjecture and its bracket
# ==========================================================================

def parse_paren(cell: str):
    """'0.0837(5)' -> (0.0837, 0.0005).  The digits in brackets are the
    uncertainty in the last digits of the mantissa."""
    m = re.fullmatch(r"(%s)\((\d+)\)" % _NUM, cell.strip())
    if not m:
        raise Drift("not a value(error) cell: %r" % cell)
    mant, unc = m.group(1), m.group(2)
    dec = len(mant.split(".")[1]) if "." in mant else 0
    return float(mant), int(unc) * 10.0 ** (-dec)


def _one(relpath, lines, pattern, why):
    """The single line matching `pattern`; returns (1-based line, match)."""
    rx, hit = re.compile(pattern), None
    for i, ln in enumerate(lines):
        m = rx.search(ln)
        if m:
            if hit is not None:
                raise Drift("%s: %r matches more than one line (needed for %s)"
                            % (relpath, pattern, why))
            hit = (i + 1, m)
    if hit is None:
        raise Drift("%s: nothing matches %r (needed for %s)" % (relpath, pattern, why))
    return hit


def build_relative_entropy():
    """docs/data/extra-relative-entropy.json.

    s2 = c/12 is a CONJECTURE.  The bracket around it is not simply "proved"
    either: the upper end holds under hypothesis (V), which is open, and the
    lower end rests on Araki's perturbation expansion, whose sources were not
    obtained (Gap RK2).  Both ends are therefore carried as conditional, with
    the hypothesis named on the record."""
    records = []

    src, lines = read("rigor/kubo_mori_gauge_lemma.tex")
    declare(src, lines,
            "The Phase-2b brief proposes the following route to $s_2=c/12$ for an arbitrary "
            "diffeomorphism covariant net.",
            "the document is still the one that brackets s2")

    ln1, m = _one(src, lines, r"\\le\\frac\{11\+5\\sqrt5\}\{24\}\\,c=(%s)\\,c" % _NUM,
                  "the upper end of the bracket")
    records.append(record("bracket.upper", float(m.group(1)), None, src, ln1, "conditional",
                          hypotheses=["(V), uniform integrability along the orbit"],
                          label="limsup s^-2 D <= (11+5 sqrt5)/24 c, Corollary 'what the route proves'",
                          note="(V) is open (Gap RK1); it holds at sigma = 0 only."))

    ln1, m = _one(src, lines, r"\\ge\\frac c\{3\\pi\^2\}=(%s)c" % _NUM,
                  "the lower end of the bracket")
    records.append(record("bracket.lower", float(m.group(1)), None, src, ln1, "conditional",
                          hypotheses=["(H3)", "Araki's perturbation expansion (Gap RK2)"],
                          label="liminf s^-2 D >= (1/2) G(M, phi) >= c/(3 pi^2)",
                          note="Gap RK2: Araki 1973 and Bratteli-Robinson II 5.4.1 were NOT "
                               "OBTAINED, so hypothesis (ii) of the lower-bound theorem is carried "
                               "as a hypothesis rather than checked."))

    ln1, m = _one(src, lines, r"\\frac\{11\+5\\sqrt5\}\{12\}\\,c\\;=\\;(%s)\\,c" % _NUM,
                  "the exact gauge infimum")
    records.append(record("gauge.inf", float(m.group(1)), None, src, ln1, "proved",
                          label="inf over stress-tensor gauges of the Kubo-Mori form = "
                                "(11+5 sqrt5)/12 c, attained in the limit at R* = (3+sqrt5)/2"))

    ln1, m = _one(src, lines, r"\\;=\\;(%s)\\times\\frac c6" % _NUM,
                  "the factor by which the gauge lemma is false")
    records.append(record("gauge.factor", float(m.group(1)), None, src, ln1, "proved",
                          label="the Phase-2b gauge lemma claimed inf = c/6; the true infimum is "
                                "larger by this factor, so the lemma is false"))

    # ---- the fermion measurement and the ladder it is extrapolated from ----
    src, lines = read("fidelity_tables.tex")
    declare(src, lines,
            "\\(s_2\\) from two-point \\(1/\\kappa_c\\) extrapolations",
            "the last row of the table is an extrapolation, not a measurement at finite kappa_c")
    declare(src, lines, "\\label{tab:second-order}", "the table the coefficients are read from")
    h = header(src, lines,
               r"\\\(\\eps\\\) & \\\(\\kappa_c\\\) & \\\(\\Lambda\\\) & \\\(\\kappa_\{\\max\}\\\) & "
               r"\\\(f_2\^\{\\rm sub\}\\\) & \\\(f_2\^\{\\rm sub\}\+\\\)tail & \\\(s_2\^\{\\rm sub\}\\\)",
               "the second-order coefficient table")
    rows = 0
    for i in range(h + 1, len(lines)):
        body = lines[i].strip()
        if body.startswith("\\bottomrule"):
            break
        if body.startswith("\\midrule") or not body:
            continue
        cells = [c.strip() for c in body.replace("\\\\", "").split("&")]
        if len(cells) != 7:
            raise Drift("fidelity_tables.tex:%d: expected 7 cells, got %d" % (i + 1, len(cells)))
        if cells[0].startswith("\\(\\to0"):
            f2, f2e = parse_paren(cells[5])
            s2, s2e = parse_paren(cells[6])
            records.append(record("fermion.f2", f2, f2e, src, i + 1, "numerical",
                                  label="free fermion f2, extrapolated to kappa_c -> infinity"))
            records.append(record("fermion.s2", s2, s2e, src, i + 1, "numerical",
                                  label="free fermion s2, a two-point 1/kappa_c extrapolation from "
                                        "the ladder below, not a measurement at finite kappa_c"))
            rows += 1
            continue
        kc = float(re.sub(r"[^0-9.]", "", cells[1]))
        records.append(record("ladder.s2.%d" % (rows + 1), float(cells[6]), None, src, i + 1,
                              "certified", series="s2_ladder", x=kc,
                              label="s2 restricted to the spectral window, kappa_c = %s "
                                    "(a rigorous lower bound, Lambda = %s)" % (kc, cells[2])))
        rows += 1
    if rows != 10:
        raise Drift("fidelity_tables.tex: expected 9 window rows and one extrapolation, read %d" % rows)

    # ---- the bosonic check ------------------------------------------------
    src, lines = read("rigor/findings.tex")
    ln1, m = _one(src, lines,
                  r"U\(1\) current net.*?f_2=(%s)\((\d+)\).*?s_2=(%s)\((\d+)\)" % (_NUM, _NUM),
                  "the bosonic check")
    f2b, f2be = parse_paren("%s(%s)" % (m.group(1), m.group(2)))
    s2b, s2be = parse_paren("%s(%s)" % (m.group(3), m.group(4)))
    records.append(record("boson.f2", f2b, f2be, src, ln1, "numerical",
                          label="U(1) current net, Gaussian mode compression in the modular frame "
                                "(numerics/boson)"))
    records.append(record("boson.s2", s2b, s2be, src, ln1, "numerical",
                          label="U(1) current net s2, the second independent net at c = 1"))

    # ---- the conjectured value itself -------------------------------------
    src, lines = read("rigor/check_note5_numerics.tex")
    ln1, m = _one(src, lines, r"s_2=1/12=(%s)" % _NUM, "the conjectured value of s2")
    records.append(record("conj.s2", float(m.group(1)), None, src, ln1, "conjectural",
                          label="s2 = c/12 at c = 1: believed, and consistent with both "
                                "measurements, but not proved for any net"))
    ln1, m = _one(src, lines, r"f_2=1/\(12\\pi\^2\)=(%s)" % _NUM, "f2 for the comparison")
    records.append(record("thm.f2", float(m.group(1)), None, src, ln1, "proved",
                          label="f2 = c/(12 pi^2) at c = 1, Theorem A: the coefficient that IS proved"))

    return {
        "generator": "tools/build_site_data_extra.py",
        "module": "relative-entropy",
        "note": ("s2 = c/12 is a conjecture.  The two ends of the bracket are conditional, not "
                 "proved: the upper end needs (V) (open), the lower end needs Araki's perturbation "
                 "expansion, whose sources were not obtained (Gap RK2 of "
                 "rigor/kubo_mori_gauge_lemma.tex).  The two measurements are at c = 1."),
        "records": records,
    }


# ==========================================================================
# module 10 — the claim map
# ==========================================================================

def _ls_files(args, why, required=True):
    try:
        out = subprocess.run(["git"] + args + ["ls-files", "-z"], cwd=str(ROOT),
                             capture_output=True, text=True, check=True).stdout
    except (OSError, subprocess.CalledProcessError) as exc:
        if required:
            raise Drift("cannot list %s (%s); the public/private test must not be "
                        "hard-coded" % (why, exc))
        return set()
    return {p for p in out.split("\0") if p}


def tracked_files():
    """(public, private): what each of the two repositories over this one work
    tree tracks.  Membership is the definition of "published": the public
    repository and the private companion share the tree, so a file being present
    on disk says nothing about whether it ships.  A file the private repository
    tracks is held privately; a file neither tracks is simply not committed yet,
    and is reported as such rather than as either."""
    public = _ls_files(["-C", str(ROOT)], "the tracked files")
    if not public:
        raise Drift("git ls-files returned nothing: refusing to mark every pointer private")
    private = _ls_files(["--git-dir", ".git-private"], "the private companion", required=False)
    return public, private


def _front_matter(path):
    """(frontmatter dict, {section title: body}) of one knowledge-base card."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        raise Drift("%s: no frontmatter" % path)
    fm = {}
    for line in m.group(1).split("\n"):
        k = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if k:
            fm[k.group(1)] = k.group(2).strip()
    body, sections, title = m.group(2), {}, None
    for line in body.split("\n"):
        h = re.match(r"^##\s+(.*)$", line)
        if h:
            title = h.group(1).strip()
            sections[title] = []
        elif title:
            sections[title].append(line)
    return fm, {k: "\n".join(v).strip() for k, v in sections.items()}


def _evidence(token, public, private):
    """Resolve one evidence token to a pointer the page can render.

    A pointer into the private companion is returned with access "private" and
    no href, so the module shows "held privately" instead of a dead link."""
    kind, _, rest = token.partition(":")
    if kind not in ("doc", "num", "ref", "ev") or not rest:
        return None
    if kind == "ev":
        return {"kind": kind, "target": rest, "access": "kb"}
    path, _, anchor = rest.partition("#")
    out = {"kind": kind, "path": path, "anchor": anchor or None}
    if path in public:
        out["access"] = "public"
    elif path in private:
        out["access"] = "private"
    elif (ROOT / path).exists():
        out["access"] = "uncommitted"
    else:
        out["access"] = "missing"
    return {k: v for k, v in out.items() if v is not None}


# A card's prose may name a file that only the private companion carries.  The map
# publishes that prose verbatim, so mark such a path rather than let it read as
# something the reader could open (REF-MOVE-1g).  The cards themselves are the
# record and are never rewritten.
_PRIVATE_PATH = re.compile(
    r"\b(PRIVATE\.md|CHECKLIST\.md|pgit-exclude|pgit|rigor/shots(?:/[A-Za-z0-9_.+-]+)?|"
    r"plan_page(?:/[A-Za-z0-9_.+-]+)?|"
    r"refs/[A-Za-z0-9_.+-]+\.pdf|rigor/cited_R[1-4]\.tex|rigor/cited_results_all\.tex)\b")


# The masking rule below is path-shaped: it looks at evidence tokens and hides the
# ones git does not track.  On 2026-09-23 REF-LIVE found a leak that was prose-shaped
# instead -- a card Statement carrying the address of a privately held Claude artifact,
# with an instruction to open it, rendered as text by module 10 and served to the world.
# A host allow-list closes the class rather than the instance: anything in a payload that
# looks like a link must point somewhere we have decided to publish.
#
# REF-LEAK then broke the first version of this guard six ways, so it no longer trusts a
# field list or a single pattern.  check_payload() sweeps the SERIALISED json, which is
# what ships, so it covers every field including the ones nobody thought of; and the host
# is taken after the last '@', because https://github.com:1234@elsewhere/ is not github.
ALLOWED_PROSE_HOSTS = {"github.com", "alexander-stottmeister.github.io",
                       "projecteuclid.org", "arxiv.org", "doi.org",
                       "creativecommons.org", "orcid.org", "www.w3.org"}
# REF-GUARD broke the previous version nine ways.  Four of them mattered and all four
# are answered here rather than by adding patterns:
#   * a label separator a browser accepts and ASCII does not -- soft hyphen, zero width,
#     fullwidth and ideographic stops -- so the text is NFKC-normalised and the invisible
#     code points are stripped BEFORE anything is matched;
#   * `?` and `#` end an authority, so they must not be inside the host class, or
#     https://elsewhere.example?@github.com reads as github.com, which is the regression
#     the fix for the userinfo trick introduced;
#   * a scheme other than http(s) is never publishable here, so it is rejected outright
#     rather than parsed, which covers file:, data:, ftp: and anything later;
#   * the bare-host branch needs a suffix list, and a short one is a hole, so it takes any
#     label of two or more letters and accepts the cost of an occasional false positive:
#     this guard may only be too strict, never too lax.
_INVISIBLE = dict.fromkeys(map(ord, "\u00ad\u200b\u200c\u200d\u2060\ufeff"))
# A deny-list, not "any scheme": prose is full of words followed by a colon, and
# http(s) is handled by the authority branch below.
_SCHEME = re.compile(r"\b(data|javascript|vbscript|file|ftp|ftps|ws|wss|blob|about|chrome|resource|view-source)\s*:", re.I)
_AUTHORITY = re.compile(r"(?:[a-z][a-z0-9+.-]*:)?//([^/?#\s)>\]\"'\\]+)", re.I)
# A bare host only counts when it is followed by a path and is not itself a path
# segment, or every dotted filename in the corpus (lb.log, README.md, x.json) is a host.
_BARE_HOST = re.compile(r"(?<![/\w.-])((?:[a-z0-9-]+\.)+[a-z]{2,})(?=/)", re.I)


def _fold(text: str) -> str:
    """What a browser would see: no invisible separators, compatibility-normalised."""
    return unicodedata.normalize("NFKC", (text or "").translate(_INVISIBLE))


def _host_of(raw: str) -> str:
    host = raw.rsplit("@", 1)[-1]                 # strip any userinfo
    return host.split(":")[0].strip().lower().rstrip(".")


def _foreign_hosts(text: str):
    """Every host in `text` that is not on the allow-list, plus any unpublishable scheme."""
    folded = _fold(text)
    for m in _SCHEME.finditer(folded):
        yield "a %s: URL" % m.group(1).lower()
    seen = set()
    for m in list(_AUTHORITY.finditer(folded)) + list(_BARE_HOST.finditer(folded)):
        host = _host_of(m.group(1))
        if host and host not in ALLOWED_PROSE_HOSTS and host not in seen:
            seen.add(host)
            yield host


def check_payload(name: str, payload) -> None:
    """Refuse to ship a payload that links off the allow-list, whatever field it is in.

    The sweep is over the SERIALISED json, which is what ships, so it covers every field
    including the ones nobody thought of -- the leak of 2026-09-23 was in a field the
    first version of this guard did not list."""
    bad = {}
    for host in _foreign_hosts(json.dumps(payload, ensure_ascii=False)):
        bad[host] = bad.get(host, 0) + 1
    if bad:
        raise Drift("docs/data/%s would publish %s. Card prose and every other field ship "
                    "verbatim to the public site; move the address somewhere private, or add "
                    "the host to ALLOWED_PROSE_HOSTS if it is meant to be published."
                    % (name, ", ".join("%d link(s) on %s" % (n, h) for h, n in sorted(bad.items()))))


def _no_foreign_url(text: str, cid: str, field: str) -> str:
    """Name the card and the field, so check_payload's message is actionable.

    The payload sweep is the guard; this is the diagnosis, and it runs first so the
    error says which card to fix rather than only which file would have shipped."""
    for host in _foreign_hosts(text):
        if True:
            raise Drift("card %s, field %s, publishes a link on %s, which is not in "
                        "ALLOWED_PROSE_HOSTS. Card prose ships verbatim to the public "
                        "site; move the address somewhere private, or add the host there "
                        "if it is meant to be published." % (cid, field, host))
    return text


def _mark_private(text: str) -> str:
    seen = set()

    def one(m):
        path = m.group(1)
        if path in seen:
            return path
        seen.add(path)
        return "%s (held privately)" % path
    return _PRIVATE_PATH.sub(one, text or "")


def build_claim_map():
    """docs/data/extra-claim-map.json: every knowledge-base card, its status,
    its evidence and the graph of the areas.

    The knowledge base itself is not published, so the module is the only public
    view of it.  Two rules are enforced here rather than in the page: a card
    whose frontmatter records no referee verdict is marked never-refereed, and
    an evidence pointer whose target is not tracked by git is marked private."""
    if not KB.is_dir():
        raise Drift("the knowledge base is not at %s" % KB)
    public, private = tracked_files()

    areas = []
    for p in sorted((KB / "areas").glob("*.md")):
        fm, _ = _front_matter(p)
        areas.append({"id": fm["id"], "title": fm.get("title", fm["id"]),
                      "status": fm.get("status", "active"),
                      "order": int(fm.get("order", "99"))})
    areas.sort(key=lambda a: (a["order"], a["id"]))
    if not areas:
        raise Drift("no areas in the knowledge base")

    cards, priv, pub, kbp, missing, never, uncommitted = [], 0, 0, 0, 0, 0, 0
    pending = 0
    priv_targets = set()
    # Which cards the map shows, and why: every card of claims/, plus a card of
    # evidence/ that has reached a displayed status, which is the rule
    # tools/build_docs.py uses for the generated pages.  Holding the two
    # surfaces to one rule is the point: a card on one and not the other would
    # be a card quietly left out.  The findings that stay behind are counted.
    PROMOTED = ("refereed", "proved", "numerical", "conjectural")
    sources = [(p, "claims") for p in sorted((KB / "claims").glob("*.md"))]
    findings_left = 0
    for p in sorted((KB / "evidence").glob("*.md")):
        fm0, _ = _front_matter(p)
        if fm0.get("status", "").strip() in PROMOTED:
            sources.append((p, "evidence"))
        else:
            findings_left += 1
    for p, origin in sources:
        fm, sec = _front_matter(p)
        review = fm.get("review", "").strip()
        verdict = re.match(r"^(passed|FAILED)\b", review)
        # A card may say "pending" while its history already records verdicts:
        # that is awaiting a re-review, which is not the same as never refereed.
        past = re.findall(r"^-\s+\S+\s+review (passed|FAILED)\b", sec.get("History", ""), re.M)
        refereed = bool(verdict) or bool(past)
        awaiting = bool(re.match(r"^pending\b", review)) or not review
        if not refereed:
            never += 1
        if awaiting:
            pending += 1
        evid = []
        for tok in re.split(r",\s*", fm.get("evidence", "")):
            tok = tok.strip()
            if not tok:
                continue
            e = _evidence(tok, public, private)
            if e is None:
                continue
            if e.get("access") == "private":
                priv_targets.add(e["path"])
            priv += e.get("access") == "private"
            pub += e.get("access") == "public"
            kbp += e.get("access") == "kb"
            missing += e.get("access") == "missing"
            uncommitted += e.get("access") == "uncommitted"
            evid.append(e)
        page = "%s.md" % fm["id"]
        cards.append({
            "id": fm["id"],
            "origin": origin,
            "title": fm.get("title", fm["id"]),
            "type": fm.get("type", "result"),
            "status": fm.get("status", "open"),
            "area": fm.get("area", "foundations"),
            "confidence": fm.get("confidence") or None,
            "statement": _no_foreign_url(
                _mark_private(sec.get("Statement", "").strip()), fm["id"], "statement"),
            "verify": _no_foreign_url(
                _mark_private(sec.get("How to verify", "").strip()), fm["id"], "verify") or None,
            "next": _no_foreign_url(
                _mark_private(fm.get("next") or ""), fm["id"], "next") or None,
            "review": review or None,
            "refereed": refereed,
            "awaiting_review": awaiting,
            "verdicts": len(past) or None,
            "review_failed": (verdict.group(1) == "FAILED") if verdict
                             else (bool(past) and past[-1] == "FAILED"),
            "page": page if ("docs/results/" + page) in public else None,
            "related": [r for r in re.split(r",\s*", fm.get("related", "")) if r],
            "evidence": evid,
        })
    if not cards:
        raise Drift("no claims in the knowledge base")

    known = {c["id"] for c in cards}
    byid = {c["id"]: c for c in cards}
    edges, seen = [], set()
    for c in cards:
        for r in c["related"]:
            if r not in known or r == c["id"]:
                continue
            key = tuple(sorted((c["id"], r)))
            if key in seen:
                continue
            seen.add(key)
            edges.append({"a": key[0], "b": key[1],
                          "cross": byid[key[0]]["area"] != byid[key[1]]["area"]})

    by_status = {}
    for c in cards:
        by_status[c["status"]] = by_status.get(c["status"], 0) + 1
    for a in areas:
        a["n"] = sum(1 for c in cards if c["area"] == a["id"])
    orphan = sorted({c["area"] for c in cards} - {a["id"] for a in areas})
    if orphan:
        raise Drift("claims in areas that have no area card: %s" % ", ".join(orphan))

    counts = [
        ("count.cards", len(cards), "cards in the knowledge base, all of them shown"),
        ("count.areas", len(areas), "areas"),
        ("count.never_refereed", never,
         "cards with no referee verdict anywhere in their record: shown, and marked never refereed"),
        ("count.awaiting_review", pending,
         "cards whose review line says pending: awaiting a pass, which is not the same as never "
         "refereed when the history already records one"),
        ("count.review_failed", sum(1 for c in cards if c["review_failed"]),
         "cards whose latest recorded verdict is a failure"),
        ("count.private_pointers", priv,
         "evidence pointers into the private companion: rendered as held privately, never as a link"),
        ("count.private_targets", len(priv_targets),
         "distinct files in the private companion that those pointers name"),
        ("count.public_pointers", pub, "evidence pointers to files git tracks, rendered as links"),
        ("count.kb_pointers", kbp,
         "evidence pointers into the knowledge base itself, which is not published"),
        ("count.missing_pointers", missing,
         "evidence pointers whose target is neither tracked nor on disk"),
        ("count.uncommitted_pointers", uncommitted,
         "evidence pointers to files that exist but neither repository tracks yet"),
        ("count.edges", len(edges), "related-to edges between cards"),
        ("count.with_page", sum(1 for c in cards if c["page"]),
         "cards that also have a generated page under docs/results/"),
        ("count.promoted", sum(1 for c in cards if c["origin"] == "evidence"),
         "cards that started as findings in the knowledge base's evidence folder and reached a "
         "displayed status"),
        ("count.findings_left", findings_left,
         "findings that stay in the knowledge base because they reached no displayed status: they "
         "are audit records, not claims"),
    ]
    records = [record(rid, value, None, "docs/data/extra-claim-map.json", 0, "numerical",
                      label=label,
                      note="counted by tools/build_site_data_extra.py from the knowledge base at "
                           "kb/projects/cft_cmi, which is not published; the line this record "
                           "links to is the count itself.")
               for rid, value, label in counts]
    for rid, value in sorted(by_status.items()):
        records.append(record("count.status." + rid, value, None,
                              "docs/data/extra-claim-map.json", 0, "numerical",
                              label="cards with status %s" % rid,
                              note="counted by tools/build_site_data_extra.py from the knowledge "
                                   "base at kb/projects/cft_cmi, which is not published."))

    payload = {
        "generator": "tools/build_site_data_extra.py",
        "module": "claim-map",
        "note": ("Every card of the private knowledge base kb/projects/cft_cmi, with its status, "
                 "its evidence and the areas as a graph.  A card with no recorded referee verdict "
                 "is marked never refereed rather than hidden, and an evidence pointer whose "
                 "target git does not track is marked held privately rather than linked: the "
                 "public repository and the private companion share one work tree, so presence "
                 "on disk is not publication."),
        "areas": areas,
        "statuses": sorted(by_status),
        "edges": edges,
        "cards": cards,
        "records": records,
    }
    return _resolve_self_lines(payload)


def _resolve_self_lines(payload):
    """The count records above are their own source: point each at the line of
    the file that carries its value.  Writing the line number back cannot move
    any line (one key per line), so one pass is exact."""
    text = json.dumps(payload, indent=1, ensure_ascii=False, sort_keys=False) + "\n"
    lines = text.split("\n")
    for rec in payload["records"]:
        needle = '"id": "%s"' % rec["id"]
        idx = [i for i, ln in enumerate(lines) if ln.strip() == needle + ","
               or ln.strip() == needle]
        if len(idx) != 1:
            raise Drift("cannot locate %s in the emitted JSON" % rec["id"])
        value_line = idx[0] - 5                      # value, error, source, line, status, id
        if not lines[value_line].strip().startswith('"value":'):
            raise Drift("unexpected key order around %s" % rec["id"])
        rec["line"] = value_line + 1
    return payload


# ==========================================================================

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="re-extract and exit non-zero if a committed JSON has drifted")
    ap.add_argument("--allow-missing-kb", action="store_true",
                    help="if the knowledge base is not beside the repository, check the "
                         "three data files that come from result files and skip the claim "
                         "map, which cannot be rebuilt without it.  Continuous integration "
                         "needs this; a working clone does not, and without the flag a "
                         "missing knowledge base is still an error.")
    args = ap.parse_args(argv)
    builders = [
        ("extra-separation.json", build_separation),
        ("extra-off-criticality.json", build_off_criticality),
        ("extra-relative-entropy.json", build_relative_entropy),
        ("extra-claim-map.json", build_claim_map),
    ]
    # The claim map is the only payload that reads the knowledge base, which is a
    # separate private repository.  Dropping it is a deliberate, announced choice,
    # never a silent one: the name of the unchecked file is printed either way.
    skipped = None
    if args.allow_missing_kb and not KB.is_dir():
        skipped = builders.pop()[0]
    try:
        payloads = [(name, fn()) for name, fn in builders]
    except Drift as exc:
        print("EXTRACTION FAILED: %s" % exc, file=sys.stderr)
        return 2
    if skipped:
        print("  NOT CHECKED, no knowledge base at %s: docs/data/%s" % (KB, skipped))
    ok = True
    for name, payload in payloads:
        ok = dump(name, payload, args.check) and ok
    if args.check and not ok:
        print("\ndocs/data/extra-*.json is out of step with the repository's result files or "
              "with the knowledge base.\nRun: python3 tools/build_site_data_extra.py",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
