#!/usr/bin/env python3
"""Generate the documentation pages under ``docs/`` from the knowledge base.

The knowledge base (a private repository of one Markdown card per claim) is the
single source of truth for what is proved, measured, conjectured or open.  This
script turns it into the public pages, so the documentation cannot drift away
from the mathematics:

    docs/index.md          the map: headline results, the pages, the claims by area
    docs/status.md         every claim, grouped by area, with status and link
    docs/results/<id>.md   one page per refereed / proved / numerical / conjectural claim
    docs/open.md           the open claims with the recorded next step, verbatim
    docs/sources.md        the table rows of refs/REFERENCES.md and how to obtain each
    docs/history.md        phases 1 to 6 and what each settled
    docs/notation.md       assembled once from the conventions appendices
    docs/definitions.md    assembled once from the conventions appendices

Everything except ``notation.md`` and ``definitions.md`` is regenerated whole on
every run.  Those two are assembled once and then left alone as soon as their
marker line says a human has edited them.

    tools/build_docs.py              regenerate docs/
    tools/build_docs.py --check      regenerate into a temporary directory and
                                     exit non-zero if the committed pages differ

Three rules this script enforces, because a documentation page can lie in ways a
status word cannot:

1.  A conditional result names its hypotheses on its own page.  Sentences of the
    card that carry a hypothesis label are quoted verbatim under "Hypotheses",
    and the status line says "Conditional" (the statement holds only under them)
    or "Stated under hypotheses" (the statement carries a hypothesis list).
2.  An evidence pointer into the private companion never becomes a dead link.
    Whether a path is public is decided by asking git whether it is tracked, not
    by a list kept in this file.
3.  A card that has never been refereed is marked as such, on its page and in
    status.md.
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DEFAULT_KB = REPO.parent / "kb" / "projects" / "cft_cmi"

# Statuses that earn a page of their own under docs/results/.
PAGE_STATUSES = ("refereed", "proved", "numerical", "conjectural")

# Display order for the status tallies; anything unknown is appended.
STATUS_ORDER = [
    "refereed", "proved", "numerical", "conjectural", "verified",
    "open", "active", "done", "superseded", "refuted", "deprecated",
]

# What each status is allowed to mean.  Kept here so that every page can repeat
# it and no reader has to guess.
STATUS_GLOSS = {
    "refereed": "a complete structured proof that an independent referee pass has accepted",
    "proved": "a complete structured proof",
    "numerical": "measured, with an error bar and a convergence order; not a theorem",
    "conjectural": "believed, with partial evidence; not proved",
    "verified": "a check that was carried out and agreed",
    "open": "an unsettled question",
    "active": "work in progress",
    "done": "a finished piece of project work",
    "superseded": "replaced by a later claim",
    "refuted": "shown to be false, kept so the correction stays visible",
    "deprecated": "no longer used",
}

# The four headline results.  Editorial choice, fixed by rigor/public_site_plan.md
# section 1; everything shown about them (title, status, hypotheses, evidence) is
# read from the knowledge base, and the build fails if one of them disappears.
HEADLINES = [
    "thm-a-quadratic-law",
    "thm-b-universality",
    "all-channel-optimum-value",
    "corner-calculus",
]

# The eight pages of the documentation subfolder, in reading order.
PAGES = [
    ("index.md", "Map of the documentation"),
    ("status.md", "Every claim, by area, with its status"),
    ("results/", "One page per consequential claim"),
    ("notation.md", "Symbols and conventions"),
    ("definitions.md", "The objects and what they mean"),
    ("open.md", "What is open, and the recorded next step"),
    ("sources.md", "External sources and how to obtain them"),
    ("history.md", "Phases 1 to 6, and the errata"),
]

BANNER = ("<!-- Generated by tools/build_docs.py from the knowledge base. "
          "Do not edit by hand: run `make docs`. -->")
HAND_EDIT_BANNER = (
    "<!-- Assembled once by tools/build_docs.py from paper1/app_conventions.tex,\n"
    "     paper2/app_conventions.tex and the conventions block of rigor/phase6_brief.md.\n"
    "     Change the next line to `hand-edited: yes` after a human pass and the\n"
    "     generator will leave this file alone. -->\n"
    "<!-- hand-edited: no -->"
)


# --------------------------------------------------------------------------- #
# knowledge-base cards
# --------------------------------------------------------------------------- #

class Card:
    """One knowledge-base card: front matter plus the body sections."""

    def __init__(self, path: Path, meta: dict, sections: dict):
        self.path = path
        self.meta = meta
        self.sections = sections
        self.id = meta.get("id", path.stem)
        self.type = meta.get("type", "")
        self.title = meta.get("title", self.id)
        self.status = meta.get("status", "")
        self.area = meta.get("area", "")
        self.review = meta.get("review", "")
        self.next = meta.get("next", "")
        self.evidence = split_list(meta.get("evidence", ""))
        self.related = split_list(meta.get("related", ""))
        self.folder = path.parent.name

    @property
    def statement(self) -> str:
        return self.sections.get("Statement", "").strip()

    @property
    def verify(self) -> str:
        return self.sections.get("How to verify", "").strip()

    @property
    def reviewed(self) -> bool:
        return bool(self.review.strip())

    @property
    def review_failed(self) -> bool:
        return self.review.strip().lower().startswith("fail")

    @property
    def review_pending(self) -> bool:
        return self.review.strip().lower().startswith("pending")

    @property
    def has_page(self) -> bool:
        return self.status in PAGE_STATUSES


def split_list(value: str) -> list:
    return [p.strip() for p in value.split(",") if p.strip()]


def parse_card(path: Path) -> Card:
    text = path.read_text(encoding="utf-8")
    meta, body = {}, text
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            front = text[3:end]
            body = text[end + 4:]
            for line in front.splitlines():
                if not line.strip() or line.lstrip().startswith("#"):
                    continue
                if ":" not in line:
                    continue
                key, value = line.split(":", 1)
                key = key.strip()
                if key and not key[0].isspace():
                    meta[key] = value.strip()
    sections, name, buf = {}, None, []
    for line in body.splitlines():
        if line.startswith("## "):
            if name is not None:
                sections[name] = "\n".join(buf).strip()
            name, buf = line[3:].strip(), []
        elif name is not None:
            buf.append(line)
    if name is not None:
        sections[name] = "\n".join(buf).strip()
    return Card(path, meta, sections)


def load_kb(kb: Path):
    """Return (claims, areas, kb_stats).  A claim is any card that carries a
    status we display: every card of claims/, plus a card of evidence/ that has
    reached one of the page statuses (findings promoted to a result live there).
    kb_stats counts the whole base, including the findings that stay behind."""
    if not (kb / "claims").is_dir():
        sys.exit(f"build_docs: no knowledge base at {kb} (pass --kb PATH)")
    claims = [parse_card(p) for p in sorted((kb / "claims").glob("*.md"))]
    every = list(claims)
    for p in sorted((kb / "evidence").glob("*.md")):
        card = parse_card(p)
        every.append(card)
        if card.has_page:
            claims.append(card)
    areas = {c.id: c for c in (parse_card(p) for p in sorted((kb / "areas").glob("*.md")))}
    kb_stats = {"cards": len(every),
                "unreviewed": sum(1 for c in every if not c.reviewed)}
    return claims, areas, kb_stats


def area_sort_key(areas: dict, area_id: str):
    card = areas.get(area_id)
    try:
        order = int(card.meta.get("order", "99")) if card else 99
    except ValueError:
        order = 99
    return (order, area_id)


# --------------------------------------------------------------------------- #
# what is public, and what is held privately
# --------------------------------------------------------------------------- #

class Repo:
    """Read-only view of which repository paths are published.

    Eight evidence targets live only in the private companion (source PDFs that
    may not be redistributed, plus the two private checklists).  They are found
    by asking git which paths this repository tracks, so the list never has to be
    maintained here and cannot go stale.
    """

    def __init__(self, root: Path):
        self.root = root
        try:
            out = subprocess.run(
                ["git", "-C", str(root), "ls-files"],
                check=True, capture_output=True, text=True).stdout
        except (OSError, subprocess.CalledProcessError) as exc:
            sys.exit("build_docs: cannot ask git which files are public "
                     f"({exc}). The private-pointer check needs it; aborting "
                     "rather than publishing links that may 404.")
        self.tracked = {line for line in out.splitlines() if line}
        self.private = []      # paths that exist but are not published
        self.missing = []      # paths that are neither published nor on disk

    def classify(self, relpath: str) -> str:
        """'public', 'private' or 'missing'."""
        if relpath in self.tracked:
            return "public"
        if (self.root / relpath).exists():
            if relpath not in self.private:
                self.private.append(relpath)
            return "private"
        if relpath not in self.missing:
            self.missing.append(relpath)
        return "missing"


# --------------------------------------------------------------------------- #
# Markdown helpers
# --------------------------------------------------------------------------- #

_ESCAPES = [
    (re.compile(r"\\"), r"\\\\"),
    (re.compile(r"`"), r"\\`"),
    (re.compile(r"\*"), r"\\*"),
    (re.compile(r"(?<![A-Za-z0-9])_"), r"\\_"),
    (re.compile(r"\["), r"\\["),
    (re.compile(r"\]"), r"\\]"),
    (re.compile(r"<"), r"\\<"),
    (re.compile(r"&(?=[A-Za-z#])"), r"\\&"),
    (re.compile(r"~"), r"\\~"),
]


def esc(text: str) -> str:
    """Escape the Markdown metacharacters, so that card text renders as itself.

    The knowledge base is plain ASCII mathematics (``V^*V``, ``[D_z, 0.71 f2
    z^2]``, ``x <= y``); without this a renderer would silently italicise or
    swallow parts of a statement, and the page would no longer be verbatim.
    """
    for pattern, repl in _ESCAPES:
        text = pattern.sub(repl, text)
    out = []
    for line in text.splitlines():
        out.append(re.sub(r"^(\s*)([-+>#=]|[0-9]+\.)", r"\1\\\2", line))
    return "\n".join(out)


def cell(text: str) -> str:
    """Escape for a table cell: as esc(), plus the column separator."""
    return esc(text).replace("|", "\\|").replace("\n", " ")


def badge(status: str) -> str:
    return f"`{status}`" if status else "`unrecorded`"


def rel_link(from_page: str, target: str) -> str:
    """Link from a page under docs/ to a repository path."""
    depth = from_page.count("/")
    return "../" * (depth + 1) + target


# --------------------------------------------------------------------------- #
# evidence, related claims, hypotheses
# --------------------------------------------------------------------------- #

KIND_LABEL = {"doc": "document", "num": "numerics", "ref": "source", "ev": "card"}


def render_evidence(token: str, repo: Repo, page: str, pages: set) -> str:
    """One evidence bullet.  Private targets are named, never linked."""
    kind, _, rest = token.partition(":")
    kind = kind.strip()
    rest = rest.strip()
    if not rest:
        return f"`{esc(token)}`"
    label = KIND_LABEL.get(kind, kind or "evidence")
    if kind == "ev":
        if rest in pages:
            return f"[{esc(rest)}]({rest}.md) — knowledge-base card"
        return f"`{esc(rest)}` — knowledge-base card, not published"
    path, _, loc = rest.partition("#")
    where = f", at `{loc.replace('`', '')}`" if loc else ""
    state = repo.classify(path)
    if state == "public":
        return f"[{esc(path)}]({rel_link(page, path)}) — {label}{where}"
    if state == "private":
        return (f"`{esc(path)}` — {label}{where}; held privately, "
                "not redistributed")
    return f"`{esc(path)}` — {label}{where}; not part of the public repository"


def render_related(target: str, by_id: dict, pages: set) -> str:
    if ":" in target:                      # cross-project reference, e.g. common:card
        return f"`{esc(target)}` — card in another knowledge base"
    card = by_id.get(target)
    if target in pages:
        title = card.title if card else target
        return f"[{esc(title)}]({target}.md) — {badge(card.status if card else '')}"
    if card:
        return f"`{esc(target)}` — {badge(card.status)}, no page of its own"
    return f"`{esc(target)}` — not in the knowledge base"


_HYP_CONTEXT = re.compile(
    r"hypothes[ei]s|hypothesis|conditional(?:ly)? on|\bunder\s+\(|\bunder\s+hypothes",
    re.IGNORECASE)
_HYP_LABEL = re.compile(r"\((H\d?'?|U)\)|\b(H[123])\b")
_HYP_RANGE = re.compile(r"\(H([0-9])\)\s*-\s*\(H([0-9])\)")
# A sentence that says a hypothesis is NOT needed must not turn the page into a
# conditional one; it may still be quoted once some other sentence establishes
# the label.
_HYP_NEGATED = re.compile(
    r"\bneither\b|\bwithout\b|\bunconditional\w*\b|\bno hypothes\w*\b|"
    r"\bdoes not (?:need|require|assume|use)\b|\bnot conditional\b",
    re.IGNORECASE)
# Says outright that the result holds only when the hypothesis does.
_HYP_CONDITIONAL = re.compile(
    r"conditional(?:ly)? on|\bunder\s+\(|\bunder\s+(?:the\s+)?\w*\s*hypothes|"
    r"\bunder\s+H[0-9]|\bonly under\b|\bmodulo\s+H[0-9]|declared hypothes|"
    r"\bassuming\b|\bsubject to\b", re.IGNORECASE)


_ABBREV = re.compile(
    r"\b(?:eq|eqs|p|pp|no|nos|prop|props|thm|thms|sec|secs|fig|figs|rem|cor|"
    r"def|lem|ex|vs|al|cf|resp|etc|approx|i\.e|e\.g)\.$", re.IGNORECASE)
_BOUNDARY = re.compile(r"(?<=[.;])\s+(?=[A-Z(\[])")


def split_sentences(text: str) -> list:
    """Sentences, without breaking at 'eq.', 'Sec.', 'i.e.' or before '(10)'."""
    text = " ".join(text.split())
    out, start = [], 0
    for m in _BOUNDARY.finditer(text):
        if _ABBREV.search(text[start:m.start()]):
            continue
        out.append(text[start:m.start()])
        start = m.end()
    out.append(text[start:])
    return [s for s in out if s]


def hypotheses(card: Card):
    """(labels, sentences) naming the hypotheses a conditional claim rests on.

    Found by reading the card, not from a table in this file.  Two passes: a
    label such as (H), (U) or H1 counts as a hypothesis label when some sentence
    both carries it and speaks of a hypothesis (or says "conditional on", "under
    (X)"); then every sentence that mentions one of those labels is quoted, so
    that the exceptions and the sufficient conditions travel with the claim.  A
    status badge alone must never be allowed to imply more than the statement
    supports.
    """
    text = card.title + ". " + card.statement
    sentences = split_sentences(text)
    labels, conditional = [], False
    for sentence in sentences:
        found = [m.group(1) or m.group(2) for m in _HYP_LABEL.finditer(sentence)]
        for lo, hi in _HYP_RANGE.findall(sentence):           # "(H1)-(H3)"
            found += [f"H{i}" for i in range(int(lo), int(hi) + 1)]
        numbered = {l for l in found if len(l) > 1}
        # A sentence establishes hypothesis labels when it speaks of hypotheses,
        # or when it simply lists two or more of them, as a theorem's hypothesis
        # list does.  A sentence that says a hypothesis is *not* needed does not.
        if not (_HYP_CONTEXT.search(sentence) or len(numbered) >= 2):
            continue
        if _HYP_NEGATED.search(sentence):
            continue
        for label in found:
            if label not in labels:
                labels.append(label)
        if found and _HYP_CONDITIONAL.search(sentence):
            conditional = True
    if not labels:
        return [], [], False
    labels.sort(key=lambda l: (len(l), l))
    mentions = re.compile("|".join(r"\(%s\)" % re.escape(l) if len(l) == 1
                                   else r"(?:\(%s\)|\b%s\b)" % (re.escape(l),
                                                                re.escape(l))
                                   for l in labels))
    quoted = [s for s in sentences if mentions.search(s)]
    return labels, quoted, conditional


def status_line(card: Card) -> str:
    labels, _, conditional = hypotheses(card)
    line = (f"**Status:** {badge(card.status)} — "
            f"{STATUS_GLOSS.get(card.status, 'see status.md')}.")
    if labels and conditional:
        line += (" **Conditional.** The statement is not unconditional: it "
                 "rests on " + ", ".join(labels) + ", quoted below. Read the "
                 "badge only together with them.")
    elif labels:
        line += (" **Stated under hypotheses** " + ", ".join(labels)
                 + ", quoted below.")
    return line


def review_line(card: Card) -> str:
    """One line, never the referee's report."""
    if not card.reviewed:
        return ("**Review record:** never refereed. No referee pass has been "
                "recorded for this card.")
    if card.review_pending:
        return ("**Review record:** a referee pass is pending; the card has no "
                "accepted verdict at present.")
    text = " ".join(card.review.split())
    verdict = "passed" if text.lower().startswith("passed") else (
        "failed" if text.lower().startswith("failed") else "recorded")
    rest = text.split(None, 1)[1] if " " in text else ""
    m = re.match(r"(\d{4}-\d{2}-\d{2})\s*(?:by\s+)?(.*)", rest)
    if m:
        when, who = m.group(1), m.group(2).strip() or "an unnamed referee"
        return f"**Review record:** {verdict} {when} by {esc(who)}."
    return f"**Review record:** {esc(text)}."


# --------------------------------------------------------------------------- #
# docs/results/<id>.md
# --------------------------------------------------------------------------- #

FOOTER = ("---\n\n[Documentation map](../index.md) · "
          "[All claims by area](../status.md) · "
          "[What is open](../open.md) · "
          "[Symbols](../notation.md) · [Definitions](../definitions.md)")


def result_page(card: Card, areas: dict, by_id: dict, pages: set, repo: Repo) -> str:
    if "/" in card.id or card.id.startswith("."):
        raise ValueError(f"card id {card.id!r} would write outside results/")
    page = f"results/{card.id}.md"
    area = areas.get(card.area)
    out = [BANNER, "", f"# {esc(card.title)}", "", status_line(card), ""]

    if not card.reviewed:
        out += ["> **Never refereed.** This card carries no referee record. "
                "It states what was found; no independent pass has tried to "
                "break it.", ""]
    elif card.review_pending:
        out += ["> **Referee pass pending.** This card has been changed since "
                "its last pass and is queued for review; the verdict below is "
                "the state of that queue, not an accepted result.", ""]
    elif card.review_failed:
        out += ["> **The last referee pass failed.** An independent pass has "
                "asked for repairs that the card has not yet absorbed. The "
                "verdict and its date are below; the report itself stays in the "
                "private knowledge base.", ""]

    bits = []
    if area:
        bits.append(f"**Area:** [{esc(area.title)}](../status.md#area-{card.area})")
    if card.type:
        bits.append(f"**Card type:** {esc(card.type)}")
    bits.append(f"**Knowledge-base id:** `{esc(card.id)}`")
    out += [" · ".join(bits), ""]

    out += ["## Statement", ""]
    out += [esc(card.statement) if card.statement else "_No statement recorded._", ""]

    labels, sentences, conditional = hypotheses(card)
    if sentences:
        out += ["## Hypotheses", "",
                ("This result is conditional: at least part of the statement "
                 "holds only where the hypotheses below hold. " if conditional else
                 "The statement is made under named hypotheses. ")
                + "The sentences are quoted from the statement above; read the "
                  "status badge only together with them.", ""]
        if labels:
            out += [f"Hypothesis labels used: {', '.join('`' + l + '`' for l in labels)}.", ""]
        for sentence in sentences:
            out.append("> " + esc(sentence).replace("\n", " "))
            out.append(">")
        out[-1] = ""

    out += ["## How to verify", ""]
    out += [esc(card.verify) if card.verify
            else "_No verification recipe recorded on this card._", ""]

    out += ["## Evidence", ""]
    if card.evidence:
        out += ["- " + render_evidence(t, repo, page, pages) for t in card.evidence]
    else:
        out.append("_No evidence tokens recorded on this card._")
    out.append("")

    out += ["## Related claims", ""]
    if card.related:
        out += ["- " + render_related(t, by_id, pages) for t in card.related]
    else:
        out.append("_None recorded._")
    out.append("")

    out += ["## Review", "", review_line(card), "",
            "The referee's report and the card's event log stay in the private "
            "knowledge base; only the verdict, the date and the referee are "
            "published here.", "", FOOTER, ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# docs/status.md
# --------------------------------------------------------------------------- #

def tally(claims: list) -> list:
    counts = {}
    for card in claims:
        counts[card.status] = counts.get(card.status, 0) + 1
    ordered = [(s, counts[s]) for s in STATUS_ORDER if s in counts]
    ordered += sorted((s, n) for s, n in counts.items() if s not in STATUS_ORDER)
    return ordered


def status_page(claims: list, areas: dict, pages: set) -> str:
    counts = tally(claims)
    total = sum(n for _, n in counts)
    unreviewed = [c for c in claims if not c.reviewed]
    failed = [c for c in claims if c.review_failed]
    pending = [c for c in claims if c.review_pending]
    promoted = [c for c in claims if c.folder == "evidence"]
    out = [BANNER, "", "# Every claim, by area", "",
           f"{total} cards: {total - len(promoted)} claim cards of the knowledge "
           f"base, plus {len(promoted)} finding"
           f"{'' if len(promoted) == 1 else 's'} that has reached a status "
           "displayed here. The tally below is counted from the cards, not "
           "typed:", "",
           "| status | claims | what it means |", "|---|---:|---|"]
    for status, n in counts:
        out.append(f"| {badge(status)} | {n} | {esc(STATUS_GLOSS.get(status, '—'))} |")
    out += [f"| **total** | **{total}** | |", ""]

    paged = sum(1 for c in claims if c.has_page)
    out += [f"{paged} of them are {', '.join(badge(s) for s in PAGE_STATUSES)} "
            "and have a page of their own under "
            "[`results/`](results/); the remainder are listed here with their "
            "status only.", "",
            "A referee pass is not implied by a status. Of the cards listed "
            f"here, **{len(unreviewed)} ha"
            f"{'s' if len(unreviewed) == 1 else 've'} never been refereed** and "
            f"**{len(failed)} carr{'ies' if len(failed) == 1 else 'y'} a failed "
            "referee pass**, that is repairs asked for and not yet absorbed. "
            "Cards awaiting a pass after a recent change are marked too, but "
            "not counted here: that number moves with day-to-day editing of "
            "infrastructure cards that have no page. "
            "All three are marked in the tables below, as *never refereed*, "
            "*referee pass failed* and *review pending*. Nothing labelled "
            f"{badge('numerical')} is a theorem.", ""]

    by_area = {}
    for card in claims:
        by_area.setdefault(card.area or "(no area)", []).append(card)
    for area_id in sorted(by_area, key=lambda a: area_sort_key(areas, a)):
        area = areas.get(area_id)
        title = area.title if area else area_id
        out += [f'<a id="area-{area_id}"></a>', "", f"## {esc(title)}", ""]
        if area and area.statement:
            out += ["> " + esc(" ".join(area.statement.split())), ""]
        out += ["| status | claim | |", "|---|---|---|"]
        rows = sorted(by_area[area_id],
                      key=lambda c: (STATUS_ORDER.index(c.status)
                                     if c.status in STATUS_ORDER else 99, c.id))
        for card in rows:
            name = (f"[{cell(card.title)}](results/{card.id}.md)"
                    if card.id in pages else cell(card.title))
            note = ("never refereed" if not card.reviewed else
                    "referee pass failed" if card.review_failed else
                    "review pending" if card.review_pending else "")
            out.append(f"| {badge(card.status)} | {name} | {note} |")
        out.append("")
    out += ["---", "",
            "[Documentation map](index.md) · [What is open](open.md) · "
            "[Sources](sources.md) · [History](history.md)", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# docs/open.md
# --------------------------------------------------------------------------- #

def open_page(claims: list, pages: set) -> str:
    def entry(card: Card) -> list:
        name = (f"### [{esc(card.title)}](results/{card.id}.md)"
                if card.id in pages else f"### {esc(card.title)}")
        mark = ("" if not card.reviewed else " · referee pass failed"
                if card.review_failed else " · review pending"
                if card.review_pending else "")
        mark = " · never refereed" if not card.reviewed else mark
        block = [name, "",
                 f"{badge(card.status)} · knowledge-base id `{esc(card.id)}`"
                 + mark, ""]
        if card.id not in pages and card.statement:
            block += [esc(card.statement), ""]
        if card.next:
            block += ["**next:** " + esc(" ".join(card.next.split())), ""]
        else:
            block += ["_No next step recorded on this card._", ""]
        return block

    openers = sorted((c for c in claims if c.status == "open"), key=lambda c: c.id)
    conj = sorted((c for c in claims if c.status == "conjectural"), key=lambda c: c.id)
    others = sorted((c for c in claims
                     if c.next and c.status in PAGE_STATUSES
                     and c.status != "conjectural"), key=lambda c: c.id)

    out = [BANNER, "", "# What is open", "",
           "Every `next:` field below is quoted verbatim from its knowledge-base "
           "card: this page records the concrete next step, not an aspiration. "
           "Project-management cards (paper edits, plans, infrastructure) are "
           "deliberately left out.", "",
           f"## Open questions ({len(openers)})", ""]
    for card in openers:
        out += entry(card)
    out += [f"## Conjectures ({len(conj)})", "",
            "Believed, with partial evidence, and not proved.", ""]
    for card in conj:
        out += entry(card)
    out += [f"## Settled claims that still record a next step ({len(others)})", "",
            "These carry a status of their own; the step recorded is what would "
            "sharpen or extend them.", ""]
    for card in others:
        out += entry(card)
    out += ["---", "",
            "[Documentation map](index.md) · [All claims by area](status.md)", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# docs/sources.md
# --------------------------------------------------------------------------- #

ARXIV = re.compile(r"arXiv:([0-9]{4}\.[0-9]{4,5}|[a-z-]+/[0-9]{7})")
URL = re.compile(r"https?://\S+")
PAYWALLED = re.compile(r"paywalled|not downloadable|\bbook\b", re.IGNORECASE)
OPEN = re.compile(r"\bopen\b", re.IGNORECASE)


def classify_source(src: str):
    """(key, sentence).  Mirrors refs/restore.sh: a row is fetchable when its
    Source column carries an arXiv identifier or a URL; of the rest, a row is
    open access when the column says so and needs library access otherwise."""
    m = ARXIV.search(src)
    if m:
        return "fetch", f"fetchable by `refs/restore.sh --fetch` (arXiv:{m.group(1)})"
    m = URL.search(src)
    if m:
        return "fetch", "fetchable by `refs/restore.sh --fetch` (direct link)"
    if PAYWALLED.search(src):
        return "library", "needs library access"
    if OPEN.search(src):
        return "open", "open access, but `refs/restore.sh` cannot resolve it automatically"
    return "library", "needs library access"


def restore_sh_says(repo_root: Path):
    """Ask refs/restore.sh itself which rows it can fetch, so the claim on the
    page is the script's own, not a reimplementation of it.  Returns a set of
    short names, or None when the script cannot be run."""
    script = repo_root / "refs" / "restore.sh"
    if not script.exists():
        return None
    try:
        out = subprocess.run(["bash", str(script), "--list"], check=True,
                             capture_output=True, text=True,
                             cwd=str(repo_root)).stdout
    except (OSError, subprocess.CalledProcessError):
        return None
    fetchable = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] in ("arXiv", "open"):
            fetchable.add(parts[1])
    return fetchable


def sources_page(repo_root: Path, warnings: list) -> str:
    text = (repo_root / "refs" / "REFERENCES.md").read_text(encoding="utf-8")
    rows, bullets = [], []
    for line in text.splitlines():
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 5 or cells[0] in ("Short",) or set(cells[0]) <= set("-: "):
                continue
            rows.append(cells)
        elif re.match(r"^- +`", line):
            bullets.append(line)

    fetchable = restore_sh_says(repo_root)
    groups = {"fetch": [], "open": [], "library": []}
    for cells in rows:
        cells = [_no_presence_claim(c) for c in cells]
        key, sentence = classify_source(cells[2])
        groups[key].append((cells, sentence))
        if fetchable is not None:
            script_says = cells[0] in fetchable
            if script_says != (key == "fetch"):
                warnings.append(f"sources.md: refs/restore.sh and this script "
                                f"disagree about {cells[0]}")

    n = len(rows)
    heuristic_note = (
        "The split between *open access* and *needs library access* is a **guess**, not a "
        "measurement: `refs/restore.sh` reports both as MANUAL, so this page classifies them "
        "by keywords in the Source column of `refs/REFERENCES.md`. Expect misfilings; at the "
        "time of writing `DaleckiiKrein` and `Petz96` are two of them. Only the *fetchable* "
        "group is verified, by comparison with a live `refs/restore.sh --list`.")
    out = [BANNER, "", "# External sources, and whether you can obtain them", "",
           heuristic_note, "",
           f"This page covers **the {n} table rows of "
           "[`refs/REFERENCES.md`](../refs/REFERENCES.md)**. It is *not* a list "
           "of every external result the project relies on: further sources are "
           f"cited in that file as bullet entries rather than table rows "
           f"({len(bullets)} of them below the table), and the source documents "
           "themselves are third-party material that this repository does not "
           "redistribute. For the full picture read "
           "[`refs/REFERENCES.md`](../refs/REFERENCES.md), which also records the "
           "exact result used from each source.", "",
           "Three ways to obtain a row:", "",
           f"| | rows | meaning |", "|---|---:|---|",
           f"| fetchable | {len(groups['fetch'])} | "
           "[`refs/restore.sh --fetch`](../refs/restore.sh) downloads it (arXiv "
           "identifier or direct link in the Source column) |",
           f"| open access | {len(groups['open'])} | freely readable at the "
           "publisher (Project Euclid, EMS Press / PRIMS), but the Source column "
           "carries no link `refs/restore.sh` can follow, so fetch it by hand |",
           f"| library access | {len(groups['library'])} | paywalled journal or a "
           "book; a library or an open restatement is needed |", "",
           "`refs/restore.sh` with no argument lists what it would download and "
           "reports everything else as `MANUAL`; it does not distinguish "
           "open-access `MANUAL` rows from paywalled ones, which is the "
           "distinction this page adds.", ""]

    titles = {"fetch": "Fetchable by `refs/restore.sh`",
              "open": "Open access, fetch by hand",
              "library": "Needs library access"}
    for key in ("fetch", "open", "library"):
        out += [f"## {titles[key]} ({len(groups[key])})", "",
                "| short | reference | source column | used in |",
                "|---|---|---|---|"]
        for cells, _ in groups[key]:
            out.append(f"| `{cell(cells[0])}` | {cell(cells[1])} | "
                       f"{cell(cells[2])} | {cell(cells[3])} |")
        out.append("")

    out += ["## What is taken from each source", "",
            "Quoted from the `Results used` column of "
            "[`refs/REFERENCES.md`](../refs/REFERENCES.md); an empty entry means "
            "the file records none.", ""]
    for cells in rows:
        used = cells[4].strip() if len(cells) > 4 else ""
        out.append(f"- **{esc(cells[0])}** — " + (esc(used) if used
                   else "_no result recorded in the table_"))
    out += ["", "---", "",
            "[Documentation map](index.md) · [All claims by area](status.md)", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# docs/history.md
# --------------------------------------------------------------------------- #

def first_sentence(text: str) -> str:
    text = " ".join(text.split())
    m = re.search(r"(?<=[.])\s+(?=[A-Z(\[])", text)
    lead = text[:m.start()] if m else text
    if lead.count("`") % 2:
        lead += "`"
    if lead.count("**") % 2:
        lead += "**"
    return lead


# A source file may assert that a PDF is "already in refs/..." or name one by path.
# Both are true of this working tree and false of a clone, where refs/*.pdf is not
# redistributed, so the generated pages drop the assertion (REF-MOVE-1b, 1c).  The
# source files themselves are historical records and are never rewritten.
def _no_presence_claim(text: str) -> str:
    text = re.sub(r"\s*\(already in [^)]*\)", "", text)
    # keep the annotation OUTSIDE any surrounding backticks: the path is code, the
    # remark about it is not (REF-MOVE-1d)
    text = re.sub(r"`refs/([A-Za-z0-9_.+-]+\.pdf)`", r"`\1` (not redistributed)", text)
    text = re.sub(r"\brefs/([A-Za-z0-9_.+-]+\.pdf)\b", r"\1 (not redistributed)", text)
    return text


def history_page(repo_root: Path, repo: Repo) -> str:
    files = sorted((repo_root / "rigor").glob("PHASE*_STATUS.md"),
                   key=lambda p: (len(p.name), p.name))
    out = [BANNER, "", "# Phases 1 to 6: what each settled", "",
           "The project ran in six phases, each opened with a brief and closed "
           "with a status file. The lead of every entry of those status files is "
           "reproduced below, in order; each phase links to its full file, which "
           "carries the numbers, the verdicts and the corrections made on the "
           "day.", ""]
    for path in files:
        rel = str(path.relative_to(repo_root))
        if repo.classify(rel) != "public":
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        title = next((l[2:].strip() for l in lines if l.startswith("# ")), path.stem)
        out += [f"## {title}", "",
                f"Source: [`{rel}`]({rel_link('history.md', rel)})", ""]
        section, bullet = None, None
        pending = []

        def flush():
            if bullet is not None:
                # a status file may name a file a clone will not have; the file itself
                # is the historical record and stays as written, the page does not
                pending.append("- " + _no_presence_claim(first_sentence(bullet)))

        for line in lines:
            if line.startswith("# "):
                continue
            if line.startswith("## "):
                flush()
                bullet = None
                if pending:
                    out.extend(pending)
                    out.append("")
                    pending = []
                section = line[3:].strip()
                out += [f"### {section}", ""]
            elif re.match(r"^[-*] ", line):
                flush()
                bullet = line[2:]
            elif bullet is not None and line.startswith(("  ", "\t")):
                bullet += " " + line.strip()
            elif line.strip() == "":
                flush()
                bullet = None
            elif line.lstrip().startswith("|"):        # a table: keep it intact
                flush()
                bullet = None
                pending.append(line.rstrip())
            else:
                flush()
                bullet = None
                pending += [first_sentence(line), ""]
        flush()
        if pending:
            out.extend(pending)
        out.append("")
    errata = "rigor/errata_log.md"
    out += ["## Errata", "",
            "Results that were wrong at some point were corrected rather than "
            "erased. Every correction is recorded, with its date and the "
            "document it touched, in "
            f"[`{errata}`]({rel_link('history.md', errata)}).", "",
            "---", "",
            "[Documentation map](index.md) · [All claims by area](status.md) · "
            "[What is open](open.md)", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# docs/notation.md and docs/definitions.md
#
# Assembled once from the two conventions appendices and the conventions block
# of the Phase 6 brief, then left alone once the marker line says a human has
# edited them.  The LaTeX is converted well enough to read; the pass that makes
# these two pages good is meant to be human.
# --------------------------------------------------------------------------- #

CONVENTION_SOURCES = ["paper1/app_conventions.tex", "paper2/app_conventions.tex",
                      "rigor/phase6_brief.md"]

# A paragraph goes to notation.md when its heading names symbols or conventions;
# everything else defines an object and goes to definitions.md.
NOTATION_KEYWORDS = ("fourier", "hardy", "inner product", "modular frame",
                     "cross-ratio variable", "central charge versus", "constant")

# Project LaTeX macros, expanded so that a plain renderer can typeset the
# formulas.  Each replacement keeps a leading space: the macros are used right
# after other commands ("\\log\\Fid") and must not fuse with them.
TEX_MACROS = [
    (r"\\Fid\b", " F"), (r"\\gB\b", " g_B"), (r"\\gKM\b", " g_{\\mathrm{KM}}"),
    (r"\\cM\b", " \\mathcal{M}"), (r"\\cN\b", " \\mathcal{N}"),
    (r"\\Tr\b", " \\operatorname{Tr}"), (r"\\one\b", " \\mathbf{1}"),
]

TEX_ACCENTS = {r'\"o': "\u00f6", r'\"a': "\u00e4", r'\"u': "\u00fc",
               r'\"O': "\u00d6", r'\"A': "\u00c4", r'\"U': "\u00dc",
               r"\'e": "\u00e9", r"\'a": "\u00e1", r"\`e": "\u00e8",
               r"\ss": "\u00df"}


def tex_to_md(tex: str) -> str:
    tex = re.sub(r"(?m)^\s*%.*$", "", tex)
    for pattern, repl in TEX_MACROS:
        tex = re.sub(pattern, lambda _m, r=repl: r, tex)
    tex = re.sub(r"\\label\{[^}]*\}", "", tex)
    tex = re.sub(r"\\(?:c|C)refrange\{([^}]*)\}\{([^}]*)\}", r"(\1 to \2)", tex)
    tex = re.sub(r"\\(?:c|C)ref\{([^}]*)\}", r"(\1)", tex)
    tex = re.sub(r"\\eqref\{([^}]*)\}", r"(\1)", tex)
    tex = re.sub(r"\\ref\{([^}]*)\}", r"(\1)", tex)
    tex = re.sub(r"\\cite\{([^}]*)\}", r"(\1)", tex)
    tex = re.sub(r"\\emph\{([^}]*)\}", r"*\1*", tex)
    tex = re.sub(r"\\textbf\{([^}]*)\}", r"**\1**", tex)
    tex = re.sub(r"\\begin\{center\}|\\end\{center\}", "", tex)
    tex = re.sub(r"\\begin\{equation\*?\}", "\n$$\n", tex)
    tex = re.sub(r"\\end\{equation\*?\}", "\n$$\n", tex)
    for accent, letter in TEX_ACCENTS.items():
        tex = tex.replace(accent, letter)
    tex = tex.replace("~", " ").replace("\\ ", " ")
    tex = re.sub(r"\\(?=\n)", "", tex)
    tex = re.sub(r"\\[,;!]", " ", tex)
    tex = re.sub(r"[ \t]+\n", "\n", tex)
    tex = re.sub(r"\n{3,}", "\n\n", tex)
    tex = re.sub(r"\$\$\n+", "$$\n", tex)
    tex = re.sub(r"\n+\$\$", "\n$$", tex)
    return tex.strip()


def tabular_to_md(tex: str) -> str:
    m = re.search(r"\\begin\{tabular\}\{[^}]*\}(.*?)\\end\{tabular\}", tex, re.S)
    if not m:
        return tex
    body = m.group(1)
    for rule in ("\\toprule", "\\midrule", "\\bottomrule"):
        body = body.replace(rule, "")
    rows = [r.strip() for r in body.split("\\\\") if r.strip()]
    table = []
    for i, row in enumerate(rows):
        cells = [" ".join(c.split()) for c in row.split("&")]
        table.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
        if i == 0:
            table.append("|" + "---|" * len(cells))
    return tex[:m.start()] + "\n" + "\n".join(table) + "\n" + tex[m.end():]


def tex_paragraphs(path: Path):
    text = path.read_text(encoding="utf-8")
    parts = re.split(r"\\paragraph\{([^}]*)\}", text)
    blocks = []
    if parts[0].strip():
        blocks.append(("", parts[0]))
    for i in range(1, len(parts), 2):
        blocks.append((parts[i].strip().rstrip("."), parts[i + 1]))
    return [(title, tex_to_md(tabular_to_md(body))) for title, body in blocks]


def phase6_conventions(path: Path):
    lines = path.read_text(encoding="utf-8").splitlines()
    block, taking = [], False
    for line in lines:
        if line.startswith("## "):
            taking = "convention" in line.lower()
            continue
        if taking:
            block.append(line)
    bullets, current = [], None
    for line in block:
        if line.startswith("- "):
            if current:
                bullets.append(current)
            current = line[2:].strip()
        elif current is not None and line.strip():
            current += " " + line.strip()
        elif current:
            bullets.append(current)
            current = None
    if current:
        bullets.append(current)
    out = []
    for text in bullets:
        head, sep, rest = text.partition(":")
        if sep and len(head) < 60:
            out.append((head.strip(), rest.strip()))
        else:
            out.append(("Chain geometry", text))
    return out


def is_notation(title: str) -> bool:
    low = title.lower()
    return any(k in low for k in NOTATION_KEYWORDS)


def conventions_pages(repo_root: Path, repo: Repo):
    notation, definitions = [], []
    for rel in CONVENTION_SOURCES:
        path = repo_root / rel
        if not path.exists() or repo.classify(rel) != "public":
            continue
        blocks = (phase6_conventions(path) if path.suffix == ".md"
                  else tex_paragraphs(path))
        for title, body in blocks:
            if not body.strip():
                continue
            target = notation if is_notation(title) else definitions
            target.append((rel, title or "Preamble", body, path.suffix))

    def render(kind: str, heading: str, blurb: str, blocks) -> str:
        caveat = ("*This page is assembled mechanically from the LaTeX conventions "
                  "appendices of the two papers and the conventions block of the "
                  "phase-6 brief. Cross-references survive only as their raw "
                  "labels, and there is no curated symbol table yet: a human pass "
                  "is still owed. Read the appendices themselves if a symbol here "
                  "is unclear.*")
        out = [HAND_EDIT_BANNER, "", f"# {heading}", "", caveat, "", blurb, "",
               "Assembled from " + ", ".join(
                   f"[`{r}`]({rel_link(kind, r)})" for r in CONVENTION_SOURCES)
               + ". Mathematics is reproduced as LaTeX; a renderer that supports "
                 "it will typeset it, and the sources above are authoritative.", ""]
        seen = None
        for rel, title, body, suffix in blocks:
            if rel != seen:
                out += [f"## From `{rel}`", ""]
                seen = rel
            out += [f"### {esc(title)}", ""]
            out += [body if suffix == ".tex" else esc(body), ""]
        out += ["---", "",
                "[Documentation map](index.md) · [All claims by area](status.md)", ""]
        return "\n".join(out)

    note = render("notation.md", "Symbols and conventions",
                  "Every constant quoted in this project depends on the choices "
                  "collected here. This page is a first assembly from the "
                  "conventions of the two papers and of the Phase 6 brief; it is "
                  "meant to be read once by a human and corrected, after which "
                  "the marker line at the top stops the generator from touching "
                  "it again.", notation)
    defn = render("definitions.md", "The objects, and what they mean",
                  "The objects the results are about: the compression map, the "
                  "stress tensor normalisation, fidelity and relative entropy, "
                  "the one-sided recovery step and the Schwarzian corner data. "
                  "Like the notation page, this is a first assembly awaiting a "
                  "human pass.", definitions)
    return note, defn


# --------------------------------------------------------------------------- #
# docs/index.md
# --------------------------------------------------------------------------- #

def index_page(claims: list, areas: dict, by_id: dict, pages: set, counts) -> str:
    out = [BANNER, "", "# Documentation map", "",
           "Conditional mutual information of adjacent intervals as a "
           "quantum-Markov defect. These pages are generated from the project's "
           "knowledge base by `tools/build_docs.py`, so what they say about a "
           "result is what the knowledge base says about it, with the same "
           "status word.", "",
           "## The four headline results", "",
           "| result | status | page |", "|---|---|---|"]
    for cid in HEADLINES:
        card = by_id.get(cid)
        if card is None or cid not in pages:
            sys.exit(f"build_docs: headline result {cid!r} is not a "
                     "knowledge-base claim with a page; fix HEADLINES or the "
                     "knowledge base rather than shipping a dead link.")
        labels, _, conditional = hypotheses(card)
        status = badge(card.status)
        if labels and conditional:
            status += " — conditional on " + ", ".join(labels)
        elif labels:
            status += " — stated under " + ", ".join(labels)
        out.append(f"| {cell(card.title)} | {status} | "
                   f"[{cell(cid)}](results/{cid}.md) |")
    out += ["",
            "A status word is a claim about how much is known, and nothing more. "
            f"{badge('numerical')} means measured, with an error bar; it is not a "
            "theorem. Where a row above says *conditional*, at least part of the "
            "statement holds only under the named hypotheses; they are quoted "
            "on the result's own page, and the badge must not be read without "
            "them. *Stated under* means the statement carries a hypothesis list "
            "of its own, quoted there as well.", "",
            "## The pages", "", "| page | what it holds |", "|---|---|"]
    for name, blurb in PAGES:
        link = f"[`{name}`]({name})" if not name.endswith("/") else f"[`{name}`]({name})"
        out.append(f"| {link} | {blurb} |")
    out += ["", "The interactive site lives in this same folder and opens at "
            "`index.html`; it is built by the other tools of `tools/` and shares "
            "these statuses.", "",
            "## Status vocabulary", "", "| status | claims | meaning |", "|---|---:|---|"]
    for status, n in counts:
        out.append(f"| {badge(status)} | {n} | {esc(STATUS_GLOSS.get(status, '—'))} |")
    out += ["",
            "## Every claim with a page, by area", "",
            "One page per claim whose status is "
            + ", ".join(badge(s) for s in PAGE_STATUSES)
            + ". The remaining claims are listed, with their status, in "
              "[`status.md`](status.md).", ""]
    by_area = {}
    for card in claims:
        if card.id in pages:
            by_area.setdefault(card.area or "(no area)", []).append(card)
    for area_id in sorted(by_area, key=lambda a: area_sort_key(areas, a)):
        area = areas.get(area_id)
        title = area.title if area else area_id
        rows = sorted(by_area[area_id],
                      key=lambda c: (STATUS_ORDER.index(c.status)
                                     if c.status in STATUS_ORDER else 99, c.id))
        out += [f"### [{esc(title)}](status.md#area-{area_id})", ""]
        for card in rows:
            mark = ("" if not card.reviewed else " — referee pass failed"
                    if card.review_failed else " — review pending"
                    if card.review_pending else "")
            mark = " — never refereed" if not card.reviewed else mark
            out.append(f"- {badge(card.status)} "
                       f"[{esc(card.title)}](results/{card.id}.md){mark}")
        out.append("")
    out += ["## How these pages are built", "",
            "`tools/build_docs.py` reads the knowledge base and writes every page "
            "here except `notation.md` and `definitions.md`, which it assembles "
            "once from the conventions appendices and then leaves alone. "
            "`tools/build_docs.py --check` regenerates into a temporary directory "
            "and fails if anything committed differs, so a page cannot drift away "
            "from the claim it describes.", "",
            "Evidence pointers that resolve into the private companion (source "
            "papers, page excerpts, and the five cited-result compendia, none of "
            "which may be redistributed) are shown as *held privately, not "
            "redistributed* instead of as links; which paths are public is "
            "decided by asking git, not by a list in the script. Statements and "
            "verification recipes are quoted verbatim, so their prose may still "
            "name such material — the page excerpts under `rigor/shots/`, the "
            "source PDFs under `refs/`, and the five cited-result compendia — "
            "which a clone will not contain; see "
            "[`THIRD-PARTY.md`](../THIRD-PARTY.md) and "
            "[`sources.md`](sources.md).", ""]
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# assembling, writing, checking
# --------------------------------------------------------------------------- #

HAND_EDIT_MARKER = re.compile(r"^[ \t]*<!--[ \t]*hand-edited:[ \t]*(yes|true)[ \t]*-->[ \t]*$",
                              re.IGNORECASE | re.MULTILINE)


def hand_edited(path: Path) -> bool:
    """True once a marker line of its own says a human has taken the file over."""
    if not path.exists():
        return False
    for line in path.read_text(encoding="utf-8").splitlines()[:20]:
        if HAND_EDIT_MARKER.match(line):
            return True
    return False


def build_all(kb: Path, repo_root: Path, docs: Path):
    claims, areas, kb_stats = load_kb(kb)
    by_id = {c.id: c for c in claims}
    pages = {c.id for c in claims if c.has_page}
    repo = Repo(repo_root)
    warnings = []

    # Sweep every claim's evidence, not only the ones that reach a page, so the
    # count of privately held targets is the project's and not this page set's.
    for card in claims:
        for token in card.evidence:
            kind, _, rest = token.partition(":")
            if kind.strip() == "ev" or not rest.strip():
                continue
            repo.classify(rest.strip().partition("#")[0])

    files = {}
    for card in claims:
        if card.has_page:
            files[f"results/{card.id}.md"] = result_page(card, areas, by_id,
                                                         pages, repo)
    counts = tally(claims)
    files["status.md"] = status_page(claims, areas, pages)
    files["open.md"] = open_page(claims, pages)
    files["sources.md"] = sources_page(repo_root, warnings)
    files["history.md"] = history_page(repo_root, repo)
    files["index.md"] = index_page(claims, areas, by_id, pages, counts)

    note, defn = conventions_pages(repo_root, repo)
    skipped_hand_edited = []
    for name, content in (("notation.md", note), ("definitions.md", defn)):
        if hand_edited(docs / name):
            warnings.append(f"{name}: marked hand-edited, left untouched")
            skipped_hand_edited.append(name)
        else:
            files[name] = content


    stats = {
        "claims": len(claims),
        "pages": len(pages),
        "private": list(repo.private),
        "missing": list(repo.missing),
        "unreviewed": sorted(c.id for c in claims if not c.reviewed),
        "unreviewed_pages": sorted(c.id for c in claims
                                   if not c.reviewed and c.has_page),
        "failed": sorted(c.id for c in claims if c.review_failed),
        "pending": sorted(c.id for c in claims if c.review_pending),
        "counts": counts,
        "kb": kb_stats,
        "warnings": warnings,
        "skipped_hand_edited": skipped_hand_edited,
    }
    return files, stats


# The generator owns exactly two things inside docs/: the top-level *.md pages it
# writes, and everything under results/.  docs/assets/, docs/explore/, docs/lib/
# and docs/data/ belong to the figure and site builders and are never scanned,
# never reported and never deleted here.
OWNED_SUBDIR = "results"
OWNED_SUFFIXES = (".md", ".markdown")


def owned(rel: str) -> bool:
    """True for a path inside docs/ that this generator is responsible for."""
    if not rel.endswith(OWNED_SUFFIXES):
        return False
    parts = rel.split("/")
    return len(parts) == 1 or parts[0] == OWNED_SUBDIR


def write_out(files: dict, docs: Path):
    (docs / "results").mkdir(parents=True, exist_ok=True)
    for name, content in sorted(files.items()):
        target = docs / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    stale = []
    for path in sorted((docs / OWNED_SUBDIR).rglob("*")):
        if not path.is_file():
            continue
        rel = path.relative_to(docs).as_posix()
        if owned(rel) and rel not in files:
            path.unlink()
            stale.append(rel)
    return stale


def check(files: dict, docs: Path, skipped=()) -> int:
    skipped = list(skipped)
    missing, extra, changed = [], [], []
    for name, content in sorted(files.items()):
        path = docs / name
        if not path.exists():
            missing.append(name)
        elif path.read_text(encoding="utf-8") != content:
            changed.append(name)
    for path in sorted(docs.rglob("*")):        # orphans, within our own scope only
        if not path.is_file():
            continue
        rel = path.relative_to(docs).as_posix()
        if owned(rel) and rel not in files and rel not in skipped:
            extra.append(rel)
    if not (missing or extra or changed):
        print(f"build_docs --check: {len(files)} pages up to date")
        if skipped:
            print("  NOT CHECKED, marked hand-edited: " + ", ".join(sorted(skipped)))
            print("  a hand-edited page is never compared, so it can go stale silently;")
            print("  re-read it, or clear the marker to put it back under the guard.")
        return 0
    print("build_docs --check: the committed documentation has drifted from the "
          "knowledge base")
    for name in missing:
        print(f"  missing   {name}")
    for name in extra:
        fixable = "" if "/" in name else "  (top level: delete it by hand)"
        print(f"  stale     {name} (no claim generates it any more){fixable}")
    for name in changed:
        print(f"  differs   {name}")
        committed = (docs / name).read_text(encoding="utf-8").splitlines()
        diff = list(difflib.unified_diff(committed, files[name].splitlines(),
                                         fromfile=f"committed/{name}",
                                         tofile=f"generated/{name}", lineterm="",
                                         n=0))
        for line in diff[:12]:
            print(f"      {line[:160]}")
        if len(diff) > 12:
            print(f"      ... {len(diff) - 12} more diff lines")
    print("\nRun `tools/build_docs.py` (or `make docs`) and commit the result.")
    return 1


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="regenerate into a temporary directory and exit "
                         "non-zero if the committed pages differ")
    ap.add_argument("--kb", type=Path, default=DEFAULT_KB,
                    help=f"knowledge-base directory (default: {DEFAULT_KB})")
    ap.add_argument("--docs", type=Path, default=REPO / "docs",
                    help="documentation folder to write (default: docs/)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)

    files, stats = build_all(args.kb, REPO, args.docs)

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            scratch = Path(tmp) / "docs"
            write_out(files, scratch)
            files = {name: (scratch / name).read_text(encoding="utf-8")
                     for name in files}
        rc = check(files, args.docs, stats.get("skipped_hand_edited", ()))
    else:
        stale = write_out(files, args.docs)
        rc = 0
        if not args.quiet:
            print(f"build_docs: wrote {len(files)} pages to {args.docs}")
            for name in stale:
                print(f"  removed stale {name}")

    if not args.quiet:
        counts = ", ".join(f"{n} {s}" for s, n in stats["counts"])
        print(f"  claims {stats['claims']} ({counts})")
        print(f"  pages under results/: {stats['pages']}")
        print(f"  evidence pointers held privately, rendered without a link: "
              f"{len(stats['private'])}")
        for path in stats["private"]:
            print(f"      {path}")
        print(f"  cards never refereed: {len(stats['unreviewed'])} of the "
              f"{stats['claims']} listed ({len(stats['unreviewed_pages'])} with "
              f"a page); {stats['kb']['unreviewed']} of the "
              f"{stats['kb']['cards']} cards in the whole knowledge base, the "
              "rest being findings that reach no displayed status")
        print(f"  cards awaiting a referee pass: {len(stats['pending'])}"
              + (" (" + ", ".join(stats["pending"]) + ")" if stats["pending"] else ""))
        print(f"  cards whose last referee pass failed: {len(stats['failed'])}"
              + (" (" + ", ".join(stats["failed"]) + ")" if stats["failed"] else ""))
        for path in stats["missing"]:
            print(f"  WARNING evidence path neither public nor on disk: {path}")
        for warning in stats["warnings"]:
            print(f"  note: {warning}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
